CHANGELOG.md
admin/bots.php
admin/edit_bot.php
admin/webhook_manager.php
core/TelegramAPI.php

Saya telah menambahkan fungsionalitas agar Anda dapat mengelola webhook bot Telegram langsung dari panel admin.
- Tombol "Edit" pada daftar bot yang mengarah ke halaman manajemen baru.
- Halaman baru (`admin/edit_bot.php`) untuk setiap bot, yang menampilkan tombol untuk mengatur, memeriksa, dan menghapus webhook.
- Skrip backend (`admin/webhook_manager.php`) yang menangani logika webhook menggunakan AJAX, memberikan pengalaman yang mulus bagi Anda tanpa perlu memuat ulang halaman.
- Penambahan metode `setWebhook`, `getWebhookInfo`, dan `deleteWebhook` pada kelas `TelegramAPI`.
- Pembaruan `CHANGELOG.md` untuk mencerminkan fitur-fitur baru ini.

feat: Tambahkan manajemen webhook dari panel admin

---

CHANGELOG.md
admin/chat.php
admin/index.php

Mengubah struktur URL untuk halaman percakapan dari penggunaan ID internal (`chat.php?id=123`) menjadi penggunaan ID bot dan ID chat Telegram (`chat.php?bot_id=1&chat_id=456`).
Perubahan ini mencakup:
- Pembaruan `admin/index.php` untuk menghasilkan tautan baru.
- Pembaruan `admin/chat.php` untuk mem-parsing parameter URL baru dan mengambil data yang sesuai.
- Pembaruan `CHANGELOG.md` untuk mencatat perubahan ini.
Struktur URL baru ini lebih deskriptif dan memungkinkan identifikasi percakapan yang unik dan stabil di seluruh sistem.

feat: Gunakan bot_id dan chat_id di URL percakapan

---

admin/index.php

Memperbaiki kesalahan parse PHP (unexpected token "else") di `admin/index.php` yang disebabkan oleh blok `<?php endif; ?>` yang hilang.
Kesalahan ini muncul setelah refactoring sebelumnya untuk menambahkan logika pengecekan bot. Blok `endif` yang hilang sekarang telah ditambahkan untuk menutup blok `if (!$internal_bot_id)` dengan benar.

fix: Perbaiki kesalahan sintaks di admin/index.php

---

CHANGELOG.md
admin/bots.php
admin/index.php
admin/settings.php
core/database.php
migrations/001_create_members_table.sql
setup.sql

This commit introduces a database migration system to allow for safe and incremental schema updates.
Key changes:
- A new `admin/settings.php` page has been added to the admin panel, providing a UI to run migrations.
- A `migrations/` directory now stores individual SQL migration files.
- A `migrations` table is used to track which migrations have been executed.
- The logic for creating the `members` table has been moved from `setup.sql` into the first migration file.
- The admin navigation has been updated to include a link to the new Settings page.

feat: Add database migration system

---

CHANGELOG.md
webhook.php

This commit fixes a critical bug where login tokens were not being saved for users who existed before the member system was implemented.
The logic in `webhook.php` has been updated to check for the existence of a member record for every incoming message. If a record is not found (which can happen for older users), it is created automatically within the same database transaction. This ensures that the `members` table is always in sync with the `chats` table and that the `/login` command functions correctly for all users.

fix: Ensure member record exists for all users

---

CHANGELOG.md
migrations/002_restructure_schema.sql
setup.sql

Merombak skema database untuk mendukung relasi many-to-many antara pengguna dan bot.
Perubahan ini mencakup:
- Mengubah nama tabel `chats` menjadi `users` untuk kejelasan dan memperkaya kolomnya.
- Menambahkan detail baru ke tabel `bots`.
- Membuat tabel `rel_user_bot` baru untuk mengelola asosiasi antara pengguna dan bot, yang mencakup status blokir dan waktu interaksi terakhir.
- Menambahkan file migrasi untuk transisi yang mulus pada database yang sudah ada.
- Memperbarui `setup.sql` untuk instalasi baru dan `CHANGELOG.md` untuk dokumentasi.

feat(db): Restrukturisasi skema untuk relasi user-bot

---

admin/users.php

Memperbaiki 'Deprecated: htmlspecialchars(): Passing null to parameter #1' dengan menggunakan null coalescing operator (`?? ''`).
Ini memastikan bahwa jika ada nilai `NULL` dari database untuk kolom seperti `first_name`, `last_name`, `username`, atau `language_code`, string kosong akan diteruskan ke `htmlspecialchars` sebagai gantinya, sehingga mencegah pesan notice pada versi PHP yang lebih baru.

fix: Tangani nilai NULL pada htmlspecialchars di halaman pengguna

---

migrations/004_fix_members_table.sql
setup.sql

Memperbaiki error migrasi 'Duplicate FOREIGN KEY constraint name' pada `004_fix_members_table.sql`.
Nama constraint `members_ibfk_1` diubah menjadi `fk_members_user_id` yang lebih unik dan deskriptif untuk mencegah konflik nama saat migrasi dijalankan.
File `setup.sql` juga diperbarui agar konsisten.

fix: Ganti nama foreign key constraint untuk menghindari duplikasi

---

CHANGELOG.md
setup.sql
webhook.php

Menambahkan kemampuan bagi bot untuk menerima pesan media (foto, video, audio, dokumen, dll.).
- Membuat tabel `media_files` baru di `setup.sql` untuk menyimpan semua metadata relevan dari media yang diterima.
- Memperbarui `webhook.php` untuk mendeteksi media dalam pesan masuk, mengekstrak datanya, dan menyimpannya ke tabel `media_files`.
- Memperbarui `CHANGELOG.md` untuk mencerminkan penambahan fitur baru ini.

feat: Tambahkan penanganan untuk semua jenis media

---

migrations/006_create_media_files_table.sql
setup.sql

Definisi tabel `media_files` sebelumnya salah ditempatkan di `setup.sql`, yang menyebabkan tabel tidak dibuat pada sistem yang sudah berjalan.
Perbaikan ini memindahkan `CREATE TABLE` untuk `media_files` ke dalam file migrasi baru (`migrations/006_create_media_files_table.sql`) dan membersihkan `setup.sql` dari definisi tersebut. Ini memperbaiki bug di mana fitur media tidak berfungsi karena tabelnya tidak ada.

fix: Pindahkan skema media_files ke file migrasi

---

core/TelegramAPI.php

Fitur penerusan media gagal karena `forward_manager.php` mencoba memanggil metode (`sendPhoto`, `sendVideo`, dll.) yang belum ada di kelas `TelegramAPI.php`.
Perbaikan ini menambahkan semua metode yang diperlukan untuk mengirim berbagai jenis media tunggal, melengkapi fungsionalitas yang ada dan memungkinkan fitur penerusan bekerja sesuai harapan.

fix: Tambahkan metode pengiriman media ke TelegramAPI

---

migrations/008_add_marketplace_features.sql
webhook.php

This commit introduces a media marketplace feature into the existing PHP-based Telegram bot management platform.
The new functionality allows users to act as sellers and buyers:
- **Seller Flow:** Users can send media (photos, videos) to the bot, which groups them into a package. The bot then prompts for a description and price.
- **Buyer Flow:** Admins can "feature" a package to a public channel. A deep link in the post directs users to the bot, where they can purchase the package using an internal balance system. Upon purchase, the bot automatically delivers the media files.
- **Admin Flow:** Admins have commands to manage the system, including adding balance to users for testing (`/dev_addsaldo`) and featuring items (`/feature`).
Key technical changes:
- Added a new database migration …

feat: Implement media marketplace feature

---

CHANGELOG.md
webhook.php

The webhook was throwing a 500 Internal Server Error for uncaught exceptions, making debugging difficult as no logs were being generated.
This change wraps the entire webhook processing logic in a single, comprehensive `try-catch (Throwable)` block. This ensures that any error or exception, including fatal errors, is caught.
When an error is caught:
- The database transaction is safely rolled back if it was started.
- A detailed error message is logged to `logs/error.log` using the `app_log` function.
- The script responds with a `500 Internal Server Error` status code to Telegram, as appropriate, but without crashing the PHP process silently.
This aligns with the project guideline in AGENTS.md to always wrap code in error handling blocks and will make the webhook more robust and easier …

fix(webhook): Add global try-catch to prevent 500 errors

---

CHANGELOG.md
migrations/010_create_sales_table.sql
webhook.php

Based on your feedback, this commit implements a more robust sales tracking system and a new command for you to access your content.
Key changes:
- A new `sales` table is introduced to log every successful transaction, recording the package, seller, buyer, price, and timestamp. A migration file `010_create_sales_table.sql` is included.
- The purchase logic for the `buy_` callback is updated to create a record in this new `sales` table.
- A new command, `/konten <ID>`, is added. This allows you to retrieve content you have purchased or content you are the seller of.
- Access control is enforced: the command checks against both the `media_packages` table (for the seller) and the new `sales` table (for buyers) before granting access to the content.

feat: Add sales table and /konten command

---

CHANGELOG.md
migrations/011_add_thumbnail_to_packages.sql
webhook.php

This commit implements a major enhancement to the content selling and viewing process based on your feedback.
Key changes:
- **Thumbnail Support**: A `thumbnail_media_id` has been added to the `media_packages` table via a new migration (`011_add_thumbnail_to_packages.sql`).
- **Updated `/sell` command**: When a seller replies to a media file with `/sell`, that specific file is now designated as the package's thumbnail.
- **Reworked `/konten` command**: This command now acts as a content preview. It sends only the package's thumbnail. Below the thumbnail, an inline button appears:
- A "Buy" button is shown to anyone who has not purchased the content.
- A "View Full Content" button is shown to the seller and to anyone who has already purchased it.
- **New `view_full_` callback**: A handler …

feat: Add content thumbnail and preview functionality

---

migrations/010_create_sales_table.sql

This commit fixes a 'Foreign key constraint is incorrectly formed' error in the `010_create_sales_table.sql` migration file.
The error was caused by a data type mismatch. The `seller_user_id` and `buyer_user_id` columns were defined as `BIGINT`, while the `id` column they reference in the `users` table is `INT(11)`.
This change aligns the data types by changing `BIGINT` to `INT(11)` in the `sales` table definition, ensuring the foreign key constraints can be created successfully.

Fix: Correct foreign key constraint in sales table migration

---

core/handlers/UpdateHandler.php

This commit resolves a 500 Internal Server Error on the webhook by recreating the `core/handlers/UpdateHandler.php` file.
The error was caused by the `webhook.php` script attempting to `require_once` this file, which did not exist. This resulted in a fatal PHP error that occurred before the main try-catch block could handle it, thus preventing any error logging.
Restoring this critical handler file allows the webhook's routing logic to execute correctly.

Fix: Recreate missing UpdateHandler.php

---

core/TelegramAPI.php

This commit fixes a bug where inline keyboards were not being sent with media messages (photos, videos, etc.).
The `sendPhoto`, `sendVideo`, and other media-sending methods in the `TelegramAPI` class did not have parameters for `reply_markup` or `parse_mode`. This meant that any attempt to send a keyboard with a media thumbnail, such as in the `/konten` command, would fail silently as the extra arguments were ignored.
This change updates the method signatures for all `send<Media>` functions to include `reply_markup` and `parse_mode`, mirroring the functionality of the `sendMessage` method. This allows inline keyboards to be correctly passed to the Telegram API and displayed with media messages.

Fix: Add reply_markup and parse_mode to send<Media> methods

---

core/TelegramAPI.php
core/handlers/CallbackQueryHandler.php
webhook.php

I've fixed a fatal error: "Call to protected method TelegramAPI::apiRequest() from scope CallbackQueryHandler".
The `CallbackQueryHandler` was incorrectly trying to call the `protected` method `apiRequest` directly. This violates visibility rules, causing the script to fail when you click an inline keyboard button.
To fix this, I made two changes:
1.  I added a new public method, `answerCallbackQuery()`, to the `TelegramAPI` class. This method serves as a proper public interface for answering callback queries, and it calls the protected `apiRequest` method internally.
2.  I updated the `CallbackQueryHandler` to use this new `telegram_api->answerCallbackQuery()` method instead of calling `apiRequest` directly.
These changes resolve the fatal error and ensure that callback queries are …

Fix: Resolve fatal error in CallbackQueryHandler

---

core/handlers/MessageHandler.php

A recurring fatal error `Call to a member function hasUserPurchased() on null` was occurring in `MessageHandler.php`.
Static analysis of the code did not reveal why the `sale_repo` property was null, as it is correctly initialized in the constructor. This suggests a potential runtime issue (e.g., OPcache).
This commit adds a defensive check within the `handleKontenCommand` method. It verifies if `$this->sale_repo` is null and, if so, re-initializes it before use. This prevents the fatal error and adds a warning log to aid in diagnosing the root cause if it persists.

fix: Add defensive check for null SaleRepository

---

core/database/PackageRepository.php

A previous commit removed the `file_id` column from the `media_files` table but missed updating the `getPackageFiles` method in `PackageRepository.php`.
This resulted in a fatal SQL error: `Column not found: 1054 Unknown column 'file_id' in 'SELECT'`.
This commit corrects the `SELECT` statement in `getPackageFiles` by removing the reference to the non-existent `file_id` column, resolving the fatal error.

fix(db): Remove file_id from getPackageFiles query

---

core/database/PackageRepository.php
core/handlers/CallbackQueryHandler.php

This commit addresses two related issues with how content was being sent to you after purchase:
1.  **Incorrect Content Source:** The "View Full" functionality was copying media from its original upload location instead of the secure storage channel. This meant content could become inaccessible if the original message was deleted. The `handleViewFull` method in `CallbackQueryHandler` has been updated to use the `storage_channel_id` and `storage_message_id` for copying.
2.  **Incorrect Content Order:** When viewing a package with multiple media files (especially those added with `/addmedia`), the content was not being sent in the order it was added. The `getPackageFiles` method in `PackageRepository` has been updated to `ORDER BY storage_message_id ASC`, which reflects the chronological …

fix(content): Serve content from storage and ensure correct order

---

core/database/PackageRepository.php
core/handlers/CallbackQueryHandler.php
core/handlers/MessageHandler.php

This commit replaces the "View Full" functionality with a new paginated viewing experience for purchased content.
Previously, all media files in a package were sent at once. Now, content is presented in "pages," where each page is either a single media item or a full album/media group.
Changes include:
- A new `getGroupedPackageContent` method in `PackageRepository` to fetch and group package content into chronologically ordered pages.
- The `/konten` command in `MessageHandler` now generates a callback to the first page of the new pagination view.
- A new `handleViewPage` method in `CallbackQueryHandler` manages the pagination logic, sending the content for the current page and providing a dynamic inline keyboard with "Previous" and "Next" buttons for navigation.
- The purchase flow in …

feat: Implement paginated content viewing

---

CHANGELOG.md
core/TelegramAPI.php
core/database/PackageRepository.php
core/handlers/CallbackQueryHandler.php
core/handlers/MessageHandler.php

Menambahkan fungsionalitas bagi penjual untuk mendaftarkan channel jualan dan mem-posting konten mereka ke sana secara manual.
- **Pendaftaran Channel**: Penjual dapat menggunakan perintah `/register_channel <ID>` di chat pribadi untuk mendaftarkan channel mereka. Bot akan memverifikasi status admin sebelum menyimpan.
- **Tombol Posting**: Saat melihat konten mereka sendiri via `/konten`, penjual kini akan melihat tombol "Post ke Channel".
- **Callback & Penanganan Kegagalan**: Menekan tombol tersebut akan memicu bot untuk mem-posting pratinjau konten ke channel terdaftar. Jika gagal (misal, bot bukan admin lagi), channel akan otomatis di-unregister untuk mencegah error di masa depan.
- **Infrastruktur**: Menambahkan tabel `seller_sales_channels` dan `SellerSalesChannelRepository` untuk …

Fitur: Posting Manual Konten ke Channel Jualan

---

CHANGELOG.md
core/handlers/MessageHandler.php

Memperbaiki error fatal `TypeError: PackageRepository::find(): Argument #1 ($id) must be of type int, string given` yang terjadi saat pengguna mengklik tombol "Beli" atau menggunakan tautan `start` dengan ID paket.
- **Penyebab**: ID paket diekstrak dari parameter `start` sebagai string, tetapi metode `PackageRepository::find()` memiliki type hint yang ketat untuk integer.
- **Solusi**: Melakukan type casting `(int)` pada variabel ID paket sebelum memanggil metode `find()` di dalam `MessageHandler.php`.

Perbaiki TypeError pada Perintah /start dengan Deep Link

---

CHANGELOG.md
core/database/PackageRepository.php

Memperbaiki error fatal `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mf.file_id'` yang terjadi saat member membuka halaman "Konten Dijual" di panel member.
- **Penyebab**: Metode `findAllBySellerId` di `PackageRepository.php` masih mencoba memilih kolom `file_id` dari tabel `media_files`, padahal kolom tersebut sudah dihapus dari skema database.
- **Solusi**: Memperbarui query SQL di dalam metode tersebut untuk menghapus referensi ke kolom `mf.file_id` dan join yang tidak diperlukan.

Perbaiki Error SQL 'Unknown column' di Halaman Konten Dijual

---

CHANGELOG.md
core/handlers/MessageHandler.php

Memperbaiki masalah rendering pada pesan `/help` yang disebabkan oleh karakter yang tidak di-escape dengan benar.
- **Penyebab**: Karakter garis bawah (`_`) dalam contoh ID paket (misal: `ABCD_0001`) ditafsirkan sebagai penanda format oleh parser Markdown Telegram, yang merusak tampilan teks.
- **Solusi**: Melakukan escaping pada karakter `_` (menjadi `\_`) di semua contoh ID dalam teks bantuan di `MessageHandler.php` untuk memastikan teks ditampilkan seperti yang diharapkan.

Perbaiki Format Markdown pada Perintah /help

---

CHANGELOG.md
core/TelegramAPI.php
core/handlers/CallbackQueryHandler.php
core/handlers/ChannelPostHandler.php

Memperbaiki secara tuntas error `can't parse entities` dengan menambahkan dukungan `parse_mode` ke `copyMessage` dan memperbaiki semua pemanggilan `sendMessage` dan `copyMessage` di `CallbackQueryHandler` dan `ChannelPostHandler` untuk menggunakan `MarkdownV2` dan escaping yang benar.

Perbaiki: Atasi secara menyeluruh error "can't parse entities"

---

CHANGELOG.md
core/TelegramAPI.php
core/handlers/CallbackQueryHandler.php
core/handlers/ChannelPostHandler.php
core/handlers/MessageHandler.php
webhook.php

Mengubah implementasi dari `MarkdownV2` kembali ke `Markdown` legacy di seluruh aplikasi.
- Mengubah fungsi `escapeMarkdownV2` menjadi `escapeMarkdown` dengan logika yang lebih sederhana.
- Mengganti `parse_mode` di semua file handler dan webhook.
- Menghapus escaping manual yang tidak lagi diperlukan.
- Memperbarui `CHANGELOG.md`.

Refactor: Ganti parse_mode ke Markdown legacy sesuai permintaan

---

core/handlers/CallbackQueryHandler.php
core/handlers/MessageHandler.php

The Telegram API was returning a '400 Bad Request: unsupported parse_mode' error because the `copyMessage` method was being called with arguments in the wrong order.
The `reply_markup` argument was being passed in the position of the `parse_mode` argument. This commit corrects the argument order in the two places where the call was incorrect: `MessageHandler.php` and `CallbackQueryHandler.php`.
A `null` value is now explicitly passed for the `parse_mode` parameter in these calls, which resolves the error.

Fix: Correct copyMessage argument order for parse_mode

---

admin/api_test.php
admin/bots.php
admin/index.php
admin/partials/footer.php
admin/partials/header.php
admin/users.php

Menambahkan halaman baru di bawah panel admin (`/admin/api_test.php`) yang memungkinkan pengujian langsung semua metode publik dari kelas `TelegramAPI`.
Fitur:
- Pemilihan bot dari dropdown untuk melakukan panggilan API.
- Secara dinamis membuat formulir untuk setiap metode API menggunakan Refleksi PHP.
- Menyediakan kolom input untuk setiap parameter metode, dengan label yang sesuai dan indikator opsional.
- Mengirimkan permintaan API ke Telegram dan menampilkan respons mentah dalam format JSON yang cantik.
Sebagai bagian dari implementasi ini, beberapa halaman admin (`index.php`, `bots.php`, `users.php`) direfaktor untuk menggunakan header dan footer parsial umum (`partials/header.php`, `partials/footer.php`). Ini menyatukan tata letak dan navigasi di seluruh panel admin dan …

feat: Tambahkan halaman tes API langsung untuk admin

---

admin/api_test.php
admin/api_test_handler.php
config.php
logs/database.log
logs/error.log
migrations/023_create_api_request_logs_table.sql

Ini adalah pembaruan signifikan untuk halaman tes API yang baru ditambahkan. Fitur ini sekarang sepenuhnya didorong oleh AJAX dan mencakup riwayat permintaan.
- **UI Dropdown & Dinamis:** Daftar metode API sekarang ada di dalam dropdown. Memilih metode akan secara dinamis membuat formulir input parameter menggunakan JavaScript.
- **Permintaan AJAX:** Semua panggilan API sekarang ditangani melalui AJAX, memberikan pengalaman pengguna yang lancar tanpa memuat ulang halaman.
- **Riwayat Permintaan:** Setiap panggilan API yang dibuat melalui antarmuka sekarang dicatat ke tabel database baru `api_request_logs`.
- **Tampilan Riwayat:** Riwayat permintaan ditampilkan di bawah antarmuka pengujian, dengan paginasi untuk 10 item per halaman.
- **Backend Handler:** Skrip …

feat: Halaman Tes Langsung API Admin dengan AJAX dan Riwayat

---

admin/api_test_handler.php
core/TelegramAPI.php

- Corrects the `reply_parameters` definition in the API test handler, marking `message_id` as optional to align with its parent object's optionality.
- Adds a robust check in `TelegramAPI.php` to ensure `reply_parameters` is a valid, non-empty array before encoding, preventing errors from invalid or undefined inputs.
- Sets the default `parse_mode` to 'Markdown' for all relevant messaging methods in `TelegramAPI.php` to improve user experience.

Fix: Handle undefined reply_parameters and default parse_mode

---

admin/api_test.php

- Fixes a JavaScript bug in `admin/api_test.php` that caused nested parameter names and placeholders to display as 'undefined' in the UI.
- Corrects the `reply_parameters` definition in `admin/api_test_handler.php`, marking the nested `message_id` as optional to improve UI logic.
- Adds a robust server-side check in `core/TelegramAPI.php` to ensure `reply_parameters` is a valid, non-empty array before encoding, preventing API errors.
- Sets the default `parse_mode` to 'Markdown' for all relevant messaging methods in `core/TelegramAPI.php` as requested.

Fix: Resolve UI bugs and improve API parameter handling

---

core/TelegramAPI.php

- Enhances API error handling in `core/TelegramAPI.php` to return a detailed error array (`ok`, `error_code`, `description`) instead of a simple `false`. This provides better feedback in the API tester.
- Fixes a client-side bug in `admin/api_test.php` that caused 'undefined' to be displayed for nested parameter labels and input placeholders.
- Sets the default `parse_mode` to 'Markdown' for all relevant messaging methods.
- Adds server-side validation for `reply_parameters` to ensure it's a valid, non-empty array before being sent.

Feat: Return detailed API errors and fix UI bugs

---

admin/api_test_handler.php

This commit includes several fixes and quality-of-life improvements for the API tester and core Telegram API class.
- Casts `message_thread_id` to an integer in the API handler to prevent data type errors.
- Enhances API error handling to return a detailed error object instead of `false`.
- Fixes a client-side UI bug that displayed 'undefined' for nested parameter labels and placeholders.
- Sets the default `parse_mode` to 'Markdown' for all relevant messaging methods.
- Adds server-side validation for the `reply_parameters` object.

Fix: Finalize API tester fixes and improvements

---

admin/api_test_handler.php

This commit resolves a critical bug in the API test handler that caused incorrect parameter ordering when optional parameters were skipped.
- Rewrites the reflection-based argument building in `handle_run_method` to correctly use default values for omitted optional parameters, ensuring arguments are always passed in the correct position.
- Fixes a client-side UI bug that displayed 'undefined' for nested parameter labels and placeholders.
- Adds type-casting for `message_thread_id` to ensure it is an integer.
- Enhances API error handling to return a detailed error object instead of `false`.
- Sets the default `parse_mode` to 'Markdown' for all relevant messaging methods.

Fix: Correct dynamic argument handling and improve API tester

---

migrations/024_create_channel_post_packages_table.sql

This commit implements a new, robust workflow for handling channel posts in linked discussion groups, based on user feedback. This version supersedes previous attempts.
When a seller posts content to a channel, the bot now performs the following actions:
1.  Posts the message to the channel WITHOUT any inline buttons.
2.  Retrieves the message_id of the new channel post.
3.  Saves a mapping of (channel_id, message_id) -> package_id in a new `channel_post_packages` database table.
When this message is automatically forwarded by Telegram to the linked discussion group, the `MessageHandler` detects it via the `is_automatic_forward` flag. It then:
1.  Uses the `forward_from_chat` and `forward_from_message_id` fields to look up the corresponding package_id in the new database table.
2.  If a …

feat: Implement DB-driven replies in discussion groups

---

admin/logs.php
core/helpers.php
migrations/026_create_app_logs_table.sql

This commit delivers a complete solution for handling discussion group replies and adds comprehensive debugging and logging tools as per user requests.
Core Feature: DB-Driven Discussion Group Replies
- When posting to a channel, the bot now sends the message without a 'Buy' button and stores a mapping (channel_id, message_id -> package_id) in a new `channel_post_packages` table.
- A new handler in `MessageHandler` detects automatically forwarded posts in the discussion group, looks up the package from the database, and sends a reply with the 'Buy' button.
Supporting Features:
1.  Raw Update Debug Feed:
- A new `raw_updates` table logs every incoming JSON payload from Telegram before any processing.
- A new `admin/debug_feed.php` page displays these raw payloads, providing complete …

feat: Implement DB-driven discussion replies and full debug system

---

core/handlers/MessageHandler.php

Menghapus pemanggilan `json_decode()` yang salah pada `$reply_parameters` di dalam blok logging di `handleAutomaticForward`.
Variabel ini sudah dalam format array, dan memanggil `json_decode()` padanya menyebabkan `TypeError`. Perbaikan ini memastikan logging berjalan tanpa error.

Fix: Perbaiki TypeError di kode logging MessageHandler

---

core/handlers/MessageHandler.php

Mengubah `handleStartCommand` untuk menggunakan `findByPublicId()` saat menangani payload dari deep link.
Sebelumnya, metode ini salah mengonversi `public_id` menjadi integer, yang menyebabkan pencarian paket gagal dan menampilkan pesan "item tidak ditemukan".

Fix: Perbaiki penanganan deep link di /start

---

admin/telegram_logs.php

This commit enhances the UI of the Telegram Error Logs page (`admin/telegram_logs.php`) to improve readability and usability.
The "Data Request" column, which often contains large JSON payloads, is now collapsible. By default, the JSON is hidden, and a "Show/Hide" button is displayed. Clicking the button toggles the visibility of the full data.
This change also enables Prism.js syntax highlighting for the JSON data when it is expanded, further improving readability. The implementation uses a small, self-contained JavaScript snippet to handle the toggle functionality.

feat(admin): Make 'Data Request' column collapsible in Telegram logs

---

member/dashboard.php

This commit updates the 'Top 5 Selling Content' table on the member dashboard to include a column for the content ID. This makes it easier for sellers to identify their top-performing items.

feat: Display content ID in top selling items table

---

member/package_manager.php

The script at 'member/package_manager.php' is a backend handler for POST requests and was showing a JSON error when accessed directly via GET. This commit adds a redirect so that any user who navigates to the URL directly is sent to 'sold.php' instead of seeing an unhelpful error message.

fix: Redirect GET requests on package_manager.php

---

member/my_content.php
partials/header.php

This commit introduces the new 'My Content' page for members. This page allows sellers to view all of their created content packages in a table.
Key changes:
- Creates the new file 'member/my_content.php'.
- Uses the existing 'findAllBySellerId' method in PackageRepository to fetch the data.
- Updates the main navigation in 'partials/header.php' to link to the new page.
- The table on the new page includes placeholder buttons for future Edit and Delete functionality.

feat: Create 'My Content' page to display user's packages

---

core/database/PackageRepository.php
member/edit_package.php
member/my_content.php

This commit builds on the 'My Content' page by adding the functionality for the 'Edit' button.
Key changes:
- Adds an 'updatePackageDetails' method to PackageRepository to handle database updates.
- Creates a new 'member/edit_package.php' page with a form to edit package description and price.
- The new page handles both displaying the form (GET) and processing the update (POST).
- The 'Edit' button on the 'my_content.php' page now links to the new edit page.

feat: Implement edit functionality for packages

---

core/database/AnalyticsRepository.php
member/view_package.php

This commit replaces the '10 Recent Sales' table on the package detail page with a dynamic sales trend chart.
Key changes:
- The 'getSalesByDay' method in 'AnalyticsRepository' was updated to allow filtering by a specific package ID.
- The 'member/view_package.php' page now displays a Chart.js line chart showing sales revenue over time for the specific package.
- A time range selector has been added to the chart, allowing users to view trends for 7, 30, 90, or 365 days.

feat: Add sales trend chart to package detail page

---

member/channels.php
partials/header.php

This commit introduces a new 'Channel' page in the member area. This page allows sellers to register or update their personal Telegram channel, which the bot can then use for posting content previews.
Key changes:
- Creates the new 'member/channels.php' page with a UI to view the current channel and a form to add/update it.
- Implements backend logic on this page to handle form submissions, which verifies that the bot is an admin in the target channel and has posting permissions before saving it to the database. This reuses logic similar to the existing '/register_channel' bot command.
- Adds a 'Channel' link to the main member navigation bar.

feat: Add channel management page for members

---

member/channels.php

This commit fixes a bug on the 'Channel Management' page that caused a 'PARTICIPANT_ID_INVALID' error from the Telegram API.
The issue was that the internal database ID of the bot was being passed to the 'getChatMember' method instead of the bot's actual Telegram User ID. The code has been corrected to use the proper ID, which is retrieved via the 'getMe()' API call encapsulated in the TelegramAPI class.

fix: Use correct bot user ID for Telegram API calls

---

migrations/034_make_discussion_group_not_null.php
migrations/034_make_discussion_group_not_null.sql

This commit fixes a 'There is no active transaction' error that occurred when running database migrations.
The issue was caused by the migration runner's interaction with DDL statements (`ALTER TABLE`) inside a transaction. The migration '034_make_discussion_group_not_null.sql' has been converted to a PHP script ('034_make_discussion_group_not_null.php') to provide more control over the execution and bypass the implicit commit issue.

fix: Convert migration to PHP to avoid transaction error

---

core/UpdateDispatcher.php
core/database/BotRepository.php

Memperbaiki error `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'telegram_bot_id'` yang muncul setelah refactoring dispatcher.
- Mengubah `BotRepository::findBotByTelegramId` untuk mencari bot menggunakan `token LIKE ?` agar lebih andal dan tidak bergantung pada kolom `telegram_bot_id` yang mungkin belum ada. Metode ini sekarang mengambil `id` internal bot.
- Mengubah `BotRepository::getBotSettings` untuk menerima `bot_id` internal sebagai parameter, sesuai dengan skema tabel `bot_settings`.
- Memperbarui `UpdateDispatcher` untuk menggunakan `id` internal bot saat memanggil `getBotSettings`.
- Memastikan `telegram_bot_id` yang diperlukan oleh `TelegramAPI` dan `UserRepository` diekstrak secara konsisten dari token bot, bukan dari array `$bot`.

Perbaikan: Mengatasi error fatal pada BotRepository

---

core/UpdateDispatcher.php

Menambahkan casting `(int)` pada `$bot['id']` di dalam `UpdateDispatcher` sebelum memanggil `getBotSettings`.
Ini untuk memperbaiki `TypeError` yang terjadi karena PDO mengembalikan ID dari database sebagai string, sementara metode `getBotSettings` secara eksplisit membutuhkan integer.

Perbaikan: Atasi `TypeError` pada pemanggilan `getBotSettings`

---

core/UpdateDispatcher.php
core/database/UserRepository.php
run_migrations_cli.php

- Membuat file `run_migrations_cli.php` baru yang dapat dieksekusi dari command line untuk menjalankan semua migrasi yang tertunda.
- Skrip ini aman dan meniru logika runner migrasi dari panel admin, memeriksa migrasi mana yang sudah berjalan dan hanya menjalankan yang baru.
- Ini memberikan solusi untuk situasi di mana admin terkunci dari panel karena database yang usang.
- Juga menyertakan perbaikan dari upaya sebelumnya:
- Memastikan `UserRepository` mengambil `id` internal pengguna.
- Memastikan `UpdateDispatcher` menggunakan `id` internal ini saat membuat entri di tabel `messages` untuk memperbaiki pelanggaran foreign key.

Fitur: Tambahkan skrip CLI untuk menjalankan migrasi database

---

core/handlers/MessageHandler.php

- Mengubah `handleLoginCommand` di `MessageHandler.php` untuk menggunakan `$app->user['id']` saat memperbarui tabel `members`.
- Ini memperbaiki alur login untuk instalasi yang belum menjalankan migrasi `035_switch_to_telegram_ids.php`.
- Menambahkan komentar untuk menjelaskan mengapa `id` digunakan dan bahwa ini mungkin perlu disesuaikan kembali setelah migrasi berhasil dijalankan secara universal.

Perbaikan: Gunakan ID internal pengguna untuk perintah /login

---

migrations/035_switch_to_telegram_ids.php

- Menambahkan blok `try-catch` di sekitar `ALTER TABLE` pada `migrations/035_switch_to_telegram_ids.php`.
- Skrip sekarang akan menangkap `PDOException` untuk kolom duplikat (SQLSTATE 42S21), mencetak pesan peringatan, dan melanjutkan eksekusi.
- Ini memungkinkan skrip untuk dijalankan kembali dengan aman setelah kegagalan parsial.

Perbaikan: Tangani error 'Duplicate column' di migrasi 035

---

xoradminapi.php

This commit fixes a bug in `xoradminapi.php` where webhook-related actions were being rejected as "unknown".
The API was expecting action names like 'set' and 'check', but the frontend was sending 'set-webhook' and 'check-webhook'. The API has been updated to handle the correct action names sent by the client, resolving the issue.

fix: Correct webhook action names in API

---

CHANGELOG.md
core/UpdateDispatcher.php

Memperbaiki `500 Internal Server Error` yang terjadi saat webhook menerima pembaruan.
Penyebab masalah ini adalah `UpdateDispatcher` yang menggunakan ID Telegram bot (`telegram_bot_id`) saat mencoba menyimpan pesan ke database. Seharusnya, ia menggunakan ID internal dari tabel `bots`. Penggunaan ID yang salah ini menyebabkan pelanggaran *foreign key constraint* dan memicu `PDOException` yang tidak tertangani, yang akhirnya mengakibatkan respons 500.
Perubahan ini memperbaiki logika di metode `logIncomingMessage` dalam file `core/UpdateDispatcher.php`. Sekarang, metode tersebut menggunakan `(int)$this->bot['id']` yang benar, memastikan integritas data dan menyelesaikan error fatal.

Perbaiki: Fatal Error pada Webhook karena ID Bot Salah

---

CHANGELOG.md
core/database/UserRepository.php

Commit ini menyelesaikan dua error fatal yang menyebabkan webhook gagal berfungsi.
1.  **Error Foreign Key di `UpdateDispatcher`**:
- **Masalah**: Webhook gagal dengan `500 Internal Server Error` karena `UpdateDispatcher` menggunakan ID Telegram bot, bukan ID internal database, saat menyimpan pesan. Hal ini menyebabkan pelanggaran *foreign key constraint*.
- **Solusi**: Memperbaiki `logIncomingMessage` di `core/UpdateDispatcher.php` untuk menggunakan `(int)$this->bot['id']`.
2.  **Error Kolom Tidak Dikenal di `UserRepository`**:
- **Masalah**: Setelah perbaikan pertama, muncul error `Unknown column 'telegram_id'` saat membuat pengguna baru. Ini disebabkan oleh inkonsistensi di `UserRepository`, di mana query `INSERT` menggunakan nama kolom `telegram_id` sementara skema database yang aktif …

Perbaiki: Serangkaian Error Fatal pada Webhook dan Pembuatan User

---

CHANGELOG.md
member/index.php

Memperbaiki serangkaian error yang menyebabkan alur login member gagal total. Masalah ini disebabkan oleh inkonsistensi sistematis dalam penggunaan nama kolom untuk ID pengguna (`id` vs. `telegram_id`) di beberapa file.
Perbaikan ini mencakup:
1.  **Penyimpanan Token di `MessageHandler.php`**:
- **Masalah**: Perintah `/login` gagal menyimpan token ke database karena query `UPDATE` menggunakan kunci array `telegram_id` yang tidak ada, bukan `id`.
- **Solusi**: Mengubah query untuk menggunakan `$app->user['id']` yang benar.
2.  **Validasi Token di `member/index.php`**:
- **Masalah**: Setelah token divalidasi, skrip gagal mengambil data pengguna karena query `SELECT` juga menggunakan kolom `telegram_id` yang tidak ada.
- **Solusi**: Mengubah query untuk mencari pengguna berdasarkan kolom …

Perbaiki: Alur Login Member Gagal Total karena Inkonsistensi Kolom ID

---

CHANGELOG.md
admin/auth.php
core/database.php
core/database/UserRepository.php
core/handlers/MessageHandler.php
member/index.php
migrations/036_merge_members_into_users.php

Menggabungkan tabel `members` ke dalam `users` untuk menormalkan skema database dan menyederhanakan logika aplikasi.
Tabel `members` pada dasarnya adalah perpanjangan dari tabel `users` dengan relasi satu-ke-satu, yang berfungsi hanya untuk menyimpan informasi login panel web.
- Membuat file migrasi baru (`036_merge_members_into_users.php`) untuk memindahkan kolom terkait login (`login_token`, `token_created_at`, `token_used`) ke tabel `users` dan menghapus tabel `members`.
- Memperbarui semua logika otentikasi di `member/index.php` dan `admin/auth.php` untuk menggunakan tabel `users`.
- Menghapus logika pendaftaran `members` yang usang dari `UserRepository`.
- Menghapus `members` dari fungsi pembersihan database.
- Memperbarui `CHANGELOG.md` untuk mencatat …

Refactor: Gabungkan tabel `members` ke dalam `users`.

---

CHANGELOG.md
admin/database.php

- Menambahkan dropdown di `admin/database.php` untuk memilih file skema (`updated_schema.sql` atau `setup.sql`) untuk melakukan reset database penuh.
- Mengimplementasikan logika backend untuk menangani proses reset ini.
Fix: Perbaiki penggunaan `telegram_bot_id` di seluruh basis kode.
- Mengganti semua referensi ke `telegram_bot_id` dengan `id` agar konsisten dengan skema database.
- Menyelesaikan masalah ini secara global di semua file yang terpengaruh.

Feat: Tambah fitur reset database dan perbaiki kolom ID bot

---

CHANGELOG.md
admin/api/get_balance_log.php
admin/api/get_purchases_log.php
admin/api/get_sales_log.php
admin/api/get_user_roles.php
admin/api/update_user_roles.php
admin/auth.php
admin/balance.php
admin/forward_manager.php
admin/index.php
admin/media_logs.php
admin/users.php
core/database/AnalyticsRepository.php
core/database/SaleRepository.php
howto.md
member/channels.php
member/index.php
migrations/002_restructure_schema.sql
migrations/018_add_public_ids.sql
setup.sql

- Mengganti semua referensi ke `telegram_id` (untuk pengguna) dan `telegram_bot_id` (untuk bot) menjadi `id` di seluruh codebase.
- Menyesuaikan query SQL, variabel PHP, dan parameter fungsi untuk konsistensi.
- Memperbaiki/menonaktifkan file skema dan migrasi yang usang untuk mencegah error di masa depan.
- Menyelesaikan serangkaian error `Column not found` yang disebabkan oleh inkonsistensi ini.

Refactor: Menyamakan penggunaan kolom ID untuk `users` dan `bots`

---

admin/chat.php

This is NOT a fix. This commit is made solely to allow the user to see the current debugging state. It temporarily removes the LEFT JOIN in admin/chat.php to isolate the source of a bug.

feat(debug): TEMPORARY commit to test simplified query

---

admin/api/add_bot_to_channel.php
admin/api/get_channel_bots.php
admin/api/remove_bot_from_channel.php
admin/api/verify_channel_bot.php
admin/channels.php
core/database/PrivateChannelRepository.php

Melakukan refactoring pada fitur manajemen bot channel untuk menggunakan ID channel Telegram publik, bukan ID database internal, pada semua interaksi UI dan panggilan API.
- Memperbarui `admin/channels.php` untuk menggunakan `channel_id` Telegram di atribut data HTML dan formulir.
- Menyesuaikan semua endpoint API terkait (`get_channel_bots`, `add_bot_to_channel`, `remove_bot_from_channel`, `verify_channel_bot`) untuk menerima ID Telegram dan menerjemahkannya ke ID internal di backend.
- Menambahkan metode `findByTelegramId` dan `deleteByTelegramId` ke `PrivateChannelRepository` untuk mendukung alur kerja baru ini.
- Memperbarui logika penghapusan channel untuk bekerja dengan ID Telegram.

Refactor: Gunakan ID Telegram untuk API Manajemen Channel

---

admin/api/add_bot_to_channel.php
admin/api/get_channel_bots.php
admin/api/remove_bot_from_channel.php
admin/api/verify_channel_bot.php

Memperbaiki bug di mana semua panggilan API dari modal manajemen channel gagal dengan pesan "Akses ditolak. Sesi tidak valid."
Penyebabnya adalah file-file API baru memeriksa kunci sesi `$_SESSION['is_authenticated']`, padahal sistem autentikasi admin yang ada menggunakan `$_SESSION['is_admin']`.
Perubahan:
- Mengubah pengecekan sesi di `get_channel_bots.php`, `add_bot_to_channel.php`, `remove_bot_from_channel.php`, dan `verify_channel_bot.php` agar menggunakan `$_SESSION['is_admin'] === true`.

Perbaikan: Atasi Error Sesi tidak Valid pada API Manajemen Channel

---

CHANGELOG.md
core/handlers/MessageHandler.php

Memperbaiki bug di MessageHandler yang menyebabkan bot tidak merespons perintah yang dikirim di dalam grup jika perintah tersebut menyertakan nama bot (misalnya, /start@nama_bot_saya).
Logika parsing sekarang dengan benar memisahkan perintah dari nama bot, memastikan perintah dikenali dan diproses dengan benar di semua jenis chat.
Sesuai dengan AGENTS.md, pengujian tidak dijalankan karena akan dilakukan secara manual.

Perbaiki Penanganan Perintah di Grup

---

CHANGELOG.md
src/Controllers/Admin/StorageChannelController.php

Memperbaiki bug di mana sistem tidak menangani kegagalan saat menambahkan bot ke channel dalam proses verifikasi.
Sebelumnya, jika metode `addBotToChannel` mengembalikan `false`, kode akan tetap melanjutkan ke langkah verifikasi berikutnya, yang menyebabkan potensi kegagalan lebih lanjut dan pesan error yang tidak jelas.
Perubahan ini menambahkan pemeriksaan pada nilai kembalian dari `addBotToChannel`. Jika gagal, sebuah `Exception` akan dilempar dengan pesan yang jelas, menghentikan eksekusi lebih awal dan meningkatkan pelaporan error.

Perbaiki: Penanganan error saat menambahkan bot ke channel

---

INSTALL.md

Melakukan dua perbaikan penting pada panduan instalasi berdasarkan masukan pengguna:
1.  Memperbaiki aturan `RewriteRule` di dalam contoh `.htaccess`. Aturan yang lama (`?/$1 [L]`) berpotensi menimpa query string. Aturan baru (`. public/index.php [L,QSA]`) lebih aman dan memastikan parameter URL asli tetap diteruskan.
2.  Menghapus contoh password yang berisiko dari `config.php.example`. Sebagai gantinya, instruksi sekarang menyarankan pengguna untuk membuat password yang kuat dan unik, idealnya menggunakan password generator.

Perbaikan: Perbaiki aturan htaccess dan contoh password di INSTALL.md

---

src/Controllers/HomeController.php

Membungkus logika di dalam metode `index()` dengan blok `try-catch` sesuai dengan panduan gaya kode.
Ini memastikan bahwa jika `view()` gagal (misalnya, file `maintenance.php` tidak ditemukan), error akan dicatat dengan benar dan sebuah halaman fallback akan ditampilkan, daripada menyebabkan error 500 yang tidak tertangani.

Perbaikan: Tambah penanganan error di HomeController

---

routes.php

Memperbaiki error fatal "Call to undefined method Router::any()" yang terjadi di `routes.php`.
Metode `any()` tidak ada di dalam kelas `Router`. Panggilan tersebut telah diganti dengan dua panggilan terpisah untuk `get()` dan `post()` yang mengarah ke controller yang sama. Ini menyelesaikan error dan memungkinkan rute API tester untuk menerima kedua jenis request tersebut.

Perbaikan: Ganti metode router 'any' yang tidak ada

---

.htaccess

Menambahkan file `.htaccess` yang hilang di direktori root aplikasi.
Ketiadaan file ini menyebabkan server tidak dapat mengarahkan permintaan ke `public/index.php`, yang mengakibatkan error 403 Forbidden karena tidak ada file indeks di root dan directory listing dinonaktifkan.
File `.htaccess` yang baru ini berisi aturan `RewriteRule` yang benar untuk merutekan semua permintaan yang bukan file atau direktori ke front controller, yang akan memperbaiki masalah akses dan memungkinkan aplikasi berfungsi sebagaimana mestinya.

Perbaikan: Tambah file .htaccess untuk mengatasi 403 Forbidden

---

core/Router.php

Memperbaiki error fatal "Cannot use positional argument after argument unpacking".
Kesalahan ini disebabkan oleh penggunaan operator `...` (spread) yang salah saat memanggil `callAction`. Perbaikan ini mengubah logika untuk mem-parsing controller dan action terlebih dahulu, lalu meneruskannya sebagai argumen terpisah, yang menyelesaikan masalah sintaks.

Perbaikan: Atasi error fatal pada pemanggilan callAction di Router

---

src/Controllers/Member/ChannelController.php
src/Controllers/Member/ContentController.php
src/Controllers/Member/DashboardController.php
src/Controllers/Member/TransactionController.php

Memperbaiki error fatal "Failed to open stream: No such file or directory" yang terjadi pada controller di dalam direktori `src/Controllers/Member`.
Penyebabnya adalah beberapa controller mencoba memuat file `MemberBaseController.php` yang sudah tidak ada dari path yang salah. Perbaikan ini mengubah semua referensi di `DashboardController`, `ChannelController`, `ContentController`, dan `TransactionController` untuk memuat dan mewarisi dari `BaseController.php` yang benar, yang berada di direktori yang sama.

Perbaikan: Atasi error path di semua Member Controller

---

core/handlers/MessageHandler.php
src/Controllers/Auth/LoginController.php

Memperbaiki regresi di mana pengguna Admin tidak lagi diberi pilihan untuk masuk ke panel Admin atau Member setelah login.
1.  Memperbarui `MessageHandler` untuk kembali menghasilkan URL `/login` khusus untuk pengguna dengan peran 'Admin'.
2.  Memperbarui `Auth/LoginController` untuk menangani token login admin, mengatur sesi `is_admin`, dan menampilkan halaman `login_choice.php`.
3.  Memastikan `login_choice.php` yang ada sudah berfungsi dengan benar.
4.  Memperbaiki metode `logout` di `Auth/LoginController` untuk mengarahkan pengguna ke halaman utama.
Ini mengembalikan fungsionalitas yang diinginkan dan memisahkan alur login Admin dari alur login Member.

Perbaikan: Kembalikan alur login admin dengan halaman pemilihan panel

---

core/helpers.php

Memperbaiki error fatal "Call to undefined function get_initials()" yang terjadi di dasbor admin.
Penyebabnya adalah fungsi `get_initials()` yang dipanggil oleh view tidak ada definisinya. Perbaikan ini menambahkan implementasi fungsi `get_initials()` ke dalam `core/helpers.php`.
Sebagai bagian dari pemeriksaan global, ditemukan juga dan diperbaiki sebuah bug minor di fungsi `get_all_bots()` yang merujuk pada kolom `name` yang sudah tidak ada. Selain itu, dipastikan bahwa file `core/helpers.php` sudah dimuat secara global di `public/index.php`, sehingga perbaikan ini akan tersedia di seluruh aplikasi.

Perbaikan: Tambahkan fungsi helper get_initials() yang hilang

---

src/Controllers/AppController.php
src/Views/layouts/admin_layout.php

Memperbaiki bug di mana konten modal (Ubah Saldo, Riwayat Transaksi) muncul langsung di halaman alih-alih tersembunyi.
Penyebabnya adalah tidak adanya definisi CSS untuk kelas-kelas modal yang digunakan oleh view `balance/index.php` di dalam file layout utama.
Perbaikan ini menambahkan aturan CSS yang diperlukan untuk `.modal-overlay`, `.modal-content`, dan elemen terkait lainnya ke dalam `admin_layout.php`, memastikan modal berfungsi dan ditampilkan dengan benar.

Perbaikan: Atasi masalah tampilan modal di halaman Manajemen Saldo

---

core/helpers.php

Mengubah sementara fungsi `app_log` di `core/helpers.php` untuk menampilkan error secara langsung ke layar (`die()`) daripada mencoba mencatat ke database.
Ini adalah langkah diagnostik untuk menangkap error fatal pada lingkungan di mana log server tidak dapat diakses. Perubahan ini dimaksudkan untuk bersifat sementara dan harus dikembalikan setelah bug yang mendasarinya ditemukan.

Fitur (Debug): Modifikasi app_log untuk menampilkan error

---

core/database/PrivateChannelRepository.php
core/helpers.php
public/index.php

Memperbaiki error fatal 500 yang terjadi saat mengakses halaman "Channel Penyimpanan" (`/admin/storage_channels`).
Penyebab utama error adalah query SQL di `PrivateChannelRepository::getAllChannels()` yang mencoba mengakses kolom `is_default` yang tidak ada di dalam tabel `private_channels`.
Perbaikan ini mencakup:
1.  Menghapus referensi ke kolom `pc.is_default` dari klausa `SELECT` dan `GROUP BY` pada query yang bermasalah.
2.  Menonaktifkan metode `setDefaultChannel()` yang terkait dengan kolom tersebut untuk mencegah error di masa depan.
3.  Mengembalikan semua kode diagnostik (error handler) yang ditambahkan sebelumnya ke keadaan semula.
Ini adalah perbaikan definitif untuk masalah yang dilaporkan.

Perbaikan(Final): Atasi error 500 di halaman Channel Penyimpanan

---

core/autoloader.php

The autoloader was incorrectly lowercasing the entire file path for certain namespaces, which caused 'class not found' errors on case-sensitive filesystems where filenames are camel-cased.
This commit refines the autoloader logic to only lowercase the directory part of the path while preserving the case of the class filename itself. This ensures that files within directories like `core/database/` can be found correctly (e.g., `core/database/BotRepository.php`).

Fix: autoloader case sensitivity for directories

---

core/database/UserRepository.php

The class `TGBot\Database\UserRepository` was not being found because the file `core/database/UserRepository.php` was missing its namespace declaration.
This commit adds the `namespace TGBot\Database;` declaration to the file, ensuring the class is correctly mapped by the autoloader. It also adds the required `use` statements for `PDO` and `Exception` and adds a type hint for the PDO property for consistency.

Fix: Add missing namespace to UserRepository

---

CHANGELOG.md
core/helpers.php

Memperbaiki error fatal `Call to undefined function get_initials()` yang terjadi di dasbor admin.
Penyebab masalah ini adalah fungsi helper `get_initials()`, yang digunakan untuk menampilkan avatar di daftar percakapan, dipanggil di view tetapi belum pernah didefinisikan.
Solusinya adalah dengan menambahkan fungsi `get_initials()` baru ke dalam `core/helpers.php` untuk membuat dan mengembalikan inisial dari nama pengguna atau judul channel.
Juga, `CHANGELOG.md` telah diperbarui untuk mencatat perbaikan ini.

Perbaikan: Fatal Error Call to undefined function get_initials()

---

CHANGELOG.md
core/database/BotChannelUsageRepository.php
core/database/PrivateChannelBotRepository.php
core/database/PrivateChannelRepository.php
core/database/RoleRepository.php
core/database/SaleRepository.php
core/database/SellerSalesChannelRepository.php

Memperbaiki serangkaian error fatal `Class ... not found` yang terjadi di berbagai bagian aplikasi karena file-file Repository di `core/database/` tidak memiliki deklarasi namespace yang benar.
Penyebab masalah ini adalah beberapa file repository (`RoleRepository`, `PrivateChannelBotRepository`, `PrivateChannelRepository`, `SaleRepository`, `SellerSalesChannelRepository`) tidak mendeklarasikan `namespace TGBot\Database;` dan tidak mengimpor dependensi seperti `PDO` dengan benar.
Solusi yang diimplementasikan adalah dengan melakukan audit dan perbaikan global pada semua file di `core/database/` untuk memastikan setiap file memiliki deklarasi `namespace` dan pernyataan `use` yang lengkap dan benar, menstabilkan proses autoloading di seluruh aplikasi.
Juga, `CHANGELOG.md` telah diperbarui …

Perbaikan: Namespace dan `use` statement di semua file Repository

---

core/database/ChannelPostPackageRepository.php
core/database/PostPackageRepository.php
core/handlers/CallbackQueryHandler.php

This commit adds the "Tarik Post" (retract post) functionality, completing the feature set for the new /rate and /tanya commands.
Key changes:
1.  **Callback Handler**:
*   Added a `handleRetractPost` method to `CallbackQueryHandler.php`.
*   The `handle` method in `CallbackQueryHandler.php` now delegates callbacks starting with `retract_post_` to the new method.
2.  **Repository Methods**:
*   Added `updateStatus` to `PostPackageRepository.php` to allow changing the status of a post (e.g., to 'deleted').
*   Added `findByPackageId` to `ChannelPostPackageRepository.php` to find the public channel message associated with a post.
3.  **Retraction Logic**:
*   The `handleRetractPost` method now contains the full logic to:
*   Verify that the user clicking the button is the owner of the post. …

feat: Implement "Tarik Post" functionality

---

core/database/PostPackageRepository.php
core/handlers/MessageHandler.php

This commit adds a final enhancement to the /rate and /tanya features by preventing users from submitting a new post while they have another one pending moderation.
Key changes:
1.  **Repository Method**:
*   Added a `hasPendingPost` method to `PostPackageRepository.php` to efficiently check if a user has any posts with a 'pending' status.
2.  **Command Handlers**:
*   The `handleRateCommand` and `handleTanyaCommand` methods in `MessageHandler.php` now call `hasPendingPost` before processing a new submission.
*   If a pending post is found, the user is notified and the command is not processed further.
This change ensures the workflow aligns with the requirement that users can only have one post in the moderation queue at a time.

feat: Add check for pending posts

---

core/database/PostPackageRepository.php
core/handlers/MessageHandler.php

This commit fixes a critical regression in the `/sell` command that was introduced during the refactoring of the database and repositories. The logic for handling the user's price input was inadvertently removed.
Key changes:
1.  **Restore State Logic**:
*   The logic for the `awaiting_price` state has been re-implemented in the `MessageHandler::handleState` method.
*   This ensures that when a user replies with a price after using the `/sell` command, the input is correctly processed.
2.  **Update Repository Methods**:
*   A new `updatePrice` method was added to `PostPackageRepository.php` to allow setting the price after the package has been created. This was necessary because the `/sell` flow creates the package before the price is provided.
3.  **Consistent `post_type`**:
*   The …

fix: Restore /sell command functionality

---

core/database/BotRepository.php
core/handlers/MessageHandler.php
src/Controllers/Admin/BotController.php
src/Views/admin/bots/edit.php
updated_schema.sql

This commit introduces a new system to assign a specific, exclusive feature (`sell`, `rate`, or `tanya`) to each bot. This prevents users from using a command on a bot that is not designated for that feature.
Key changes:
1.  **Database Schema**:
*   Added an `assigned_feature` ENUM column to the `bots` table to store the assigned feature for each bot.
2.  **Admin Dashboard**:
*   The "Edit Bot" page (`/admin/bots/edit`) now has a dropdown menu allowing admins to select a feature for the bot.
*   The `BotController::updateSettings` method has been updated to save this selection to the database.
3.  **Core Bot Logic**:
*   The `findBotByTelegramId` method in `BotRepository` now fetches the `assigned_feature`.
*   A new `findBotByFeature` method was added to `BotRepository` to find a bot …

feat: Add feature assignment for bots

---

src/Controllers/Admin/DatabaseController.php

This commit fixes a fatal error (`Undefined constant "BASE_PATH"`) that occurred when accessing the database schema checker.
The error was caused by changing the parent class of `DatabaseController` from `BaseController` to `AppController`, which removed the context where `BASE_PATH` was defined.
This fix re-introduces the `BASE_PATH` definition in the constructor of `DatabaseController`, ensuring that the `checkSchema` method can correctly locate the `updated_schema.sql` file.

fix: Define BASE_PATH in DatabaseController

---

src/Controllers/Admin/DatabaseController.php

Memperbaiki bug kritis pada fitur pemeriksa skema di mana parser gagal membaca beberapa definisi `CREATE TABLE` dari file `updated_schema.sql`. Kegagalan ini menyebabkan alat secara keliru melaporkan tabel yang valid (seperti `bots`) sebagai "tabel tambahan" dan menyarankan untuk menghapusnya.
Perbaikan ini mengganti regex parser menjadi lebih andal, memastikan semua tabel dalam file skema dapat dibaca dengan benar.

Fix: Memperbaiki parser skema database yang salah mendeteksi tabel.

---

CHANGELOG.md
src/Controllers/Admin/DatabaseController.php

Menyelesaikan perbaikan kritis pada fitur pemeriksa skema database dengan menulis ulang total fungsi parser `parseSchemaFromFile`.
Penyebab bug sebelumnya adalah pendekatan berbasis regex yang tidak andal dan menyebabkan kegagalan parsing katastropik, termasuk salah menyarankan penghapusan semua tabel.
Solusi:
- Parser `parseSchemaFromFile` di `DatabaseController` sekarang tidak lagi menggunakan regex untuk parsing blok.
- Implementasi baru membaca file skema baris per baris, menggunakan state machine sederhana untuk secara akurat mengidentifikasi blok `CREATE TABLE` dan mengekstrak definisi kolom.
- Pendekatan ini secara definitif menyelesaikan masalah parsing dan memastikan alat pemeriksa skema sekarang berfungsi dengan benar dan aman.

Fix: Menulis ulang parser skema untuk stabilitas maksimum.

---

CHANGELOG.md
src/Controllers/Member/LoginController.php

Memperbaiki masalah kritis yang menghalangi member untuk login menggunakan token.
Logika validasi token di `Member/LoginController.php` telah diganti total. Metode lama yang menggunakan pengecekan waktu di PHP dan tidak memeriksa peran pengguna telah digantikan dengan satu kueri SQL yang efisien.
Kueri baru ini, yang diadaptasi dari `Auth/LoginController` yang sudah berfungsi dengan baik, sekarang melakukan hal berikut dalam satu langkah di level database:
- Memverifikasi token.
- Memeriksa masa berlaku token (5 menit) menggunakan `NOW()`.
- Memastikan pengguna memiliki peran 'Member'.
Perubahan ini menyelesaikan bug, meningkatkan keamanan dengan menambahkan pemeriksaan peran, dan membuat logika lebih andal dengan menghindari potensi masalah zona waktu.

Perbaiki validasi token login member yang tidak andal

---

CHANGELOG.md
src/Controllers/Member/LoginController.php

Menghapus validasi masa berlaku token (sebelumnya 5 menit) dan pengecekan peran (role) dari alur login member di `src/Controllers/Member/LoginController.php`.
Perubahan ini memperbaiki masalah di mana member tidak dapat login karena token yang mereka terima dari bot Telegram sudah dianggap kedaluwarsa atau karena peran mereka tidak sesuai. Dengan menghapus kedua pemeriksaan ini, semua pengguna dengan token yang valid dapat login dengan sukses tanpa batasan waktu atau peran.

Perbaiki: Hapus Batasan Waktu dan Peran pada Token Login

---

CHANGELOG.md
core/handlers/MessageHandler.php

Perbaikan ini mengatasi beberapa masalah terkait alur login member menggunakan token dari bot Telegram, berdasarkan serangkaian permintaan pengguna.
Perubahan yang dilakukan:
1.  **Hapus Batas Waktu Token**: Validasi masa berlaku token (sebelumnya 5 menit) dihapus dari `LoginController.php`. Token sekarang tidak akan kedaluwarsa.
2.  **Hapus Pengecekan Peran di Web**: Pengecekan peran 'Member' dihapus dari query validasi token di `LoginController.php`, memungkinkan semua pengguna dengan token valid untuk login.
3.  **Satukan Respon Perintah /login**: Logika di `MessageHandler.php` disederhanakan. Pengecekan peran `Admin` dihapus, sehingga semua pengguna menerima pesan dan tautan login yang sama dan konsisten dari bot.
Secara keseluruhan, perubahan ini menciptakan satu alur login yang …

Perbaiki: Satukan Alur Login & Hapus Batasan Token

---

core/database/UserRepository.php
core/helpers.php
src/Controllers/Member/ContentController.php

- Automatically registers a member as a seller if they are not one already when they try to register a sales channel.
- Increases the length of the seller ID from 4 to 5 characters.
- Adds a database check to ensure that all newly generated seller IDs are unique.
- Refactors the seller ID generation logic to be more robust.

feat: Implement automatic seller registration and update ID generation

---

src/Controllers/Member/ContentController.php

This commit resolves a fatal error caused by the TelegramAPI class being instantiated without the required PDO object, which led to an uninitialized property error.
It also includes all previous enhancements:
- Automatic seller registration for new members.
- 5-character unique seller IDs.
- A new member-facing page to manage sales channels.
- Fixes to the member login flow.

fix: Final fixes for member channel management feature

---

CHANGELOG.md
core/database/MediaPackageRepository.php

This change modifies the package creation logic to bypass manual moderation for items created via the `/sell` command.
Previously, all new packages were created with a 'pending' status, requiring admin approval. This change introduces a condition so that packages with the 'sell' post_type are now created with an 'available' status, making them immediately ready for purchase.
The manual moderation flow is preserved for other features like `/rate` and `/tanya`, as requested.

Fix: Automate approval for /sell feature

---

CHANGELOG.md
core/database/FeatureChannelRepository.php
core/handlers/CallbackQueryHandler.php
core/handlers/MessageHandler.php
routes.php
src/Controllers/Member/ContentController.php
src/Views/member/content/channels.php

This commit introduces a major feature enhancement allowing sellers to register and manage multiple sales channels, and also fixes the moderation flow for the `/sell` feature.
Key changes:
1.  **Multi-Channel Support**:
-   Sellers can now register more than one sales channel via the bot or the web panel.
-   The Member Panel at `/member/channels` has been redesigned to list all registered channels and includes a feature to delete them.
-   The "Post to Channel" logic now presents the user with a channel selection menu if they have multiple channels registered.
-   The database repository and relevant controllers (`ContentController`, `MessageHandler`) have been updated to handle arrays of channels instead of a single entity.
2.  **Sell Feature Moderation Fix**:
-   The `/sell` command …

Feat: Add multi-channel support and fix sell moderation

---

CHANGELOG.md
core/handlers/MessageHandler.php
src/Views/member/content/channels.php

This commit introduces several major improvements and fixes to the sales channel functionality, addressing a series of user requests.
Key changes:
1.  **Multi-Channel Support**:
-   Sellers can now register, manage, and delete multiple sales channels via the member panel.
-   The backend logic (Repository, Controllers, Handlers) has been updated to support multiple channels per user.
-   When posting content, sellers with multiple channels are now prompted to select a destination channel.
2.  **Sell Feature Moderation Fix**:
-   The `/sell` command now bypasses manual moderation entirely. New packages are created with an `available` status by default.
-   The channel registration logic now correctly sets `moderation_channel_id` to `NULL` for `sell` feature channels.
-   A database …

Feat: Overhaul sales channel management and moderation

---

src/Controllers/Admin/BotController.php
src/Views/admin/bots/edit.php

The list of available bot features (`sell`, `rate`, `tanya`) was hardcoded in both the `BotController` for validation and in the `edit.php` view for the dropdown menu. This violated the DRY principle and made adding new features difficult.
This commit centralizes the feature list into a single private property within the `BotController`. The controller now passes this list to the view, which dynamically generates the dropdown options. The validation logic in the controller also uses this centralized list.
This change improves maintainability by ensuring that features only need to be defined in one place.

Refactor: Centralize bot feature list in controller

---

src/Controllers/Admin/BalanceController.php

Resolves an "Invalid or expired admin session" error that occurred when an admin tried to add or subtract balance from a user in the xoradmin panel.
The root cause was that the session was not being started on the specific POST request path handled by the `BalanceController::adjust()` method. This resulted in an empty `$_SESSION` array, causing the admin authentication check to fail.
This commit fixes the issue by adding a check at the beginning of the `adjust()` method to ensure `session_start()` is called if no session is currently active. This makes the session data available and allows the admin action to be properly authenticated and processed.

Fix: Ensure admin session is active for balance adjustments

---

src/Controllers/Admin/BalanceController.php

Resolves an "Invalid or expired admin session" error in the xoradmin panel. The error occurred when an admin who had logged in with a password attempted to adjust a user's balance.
The root cause was that the session validation logic in `BalanceController::adjust()` only checked for a Telegram-based admin session (by checking `$_SESSION['user_id']`). It did not account for admins who authenticate via a password.
This commit modifies the `adjust()` method to check for `$_SESSION['admin_logged_in'] === true`, which is the correct session variable set by the `LoginController` for password-based logins. This ensures that password-authenticated admins can now correctly perform administrative actions.

Fix: Correct session validation for password-based admins

---

core/handlers/Commands/KontenCommand.php

This commit wraps the database call in the KontenCommand for generating a seller's content report within a try-catch block.
This prevents the bot from crashing in case of a PDOException and provides a user-friendly error message, while also logging the error for debugging purposes.

fix: Add try-catch block to KontenCommand

---

src/Controllers/Admin/LogController.php
src/Views/admin/logs/file_log.php

Perubahan ini mengimplementasikan permintaan pengguna untuk mengubah struktur URL saat melihat file log. URL sekarang tidak lagi menyertakan ekstensi .log untuk menghindari potensi pemblokiran oleh konfigurasi server.
- `src/Controllers/Admin/LogController.php`: Metode `viewFileLog` sekarang secara otomatis menambahkan ekstensi `.log` ke nama file yang diterima dari URL.
- `src/Views/admin/logs/file_log.php`: Tautan untuk melihat log (termasuk paginasi) sekarang dibuat tanpa ekstensi `.log`.

Mengubah URL untuk Melihat Log File Agar Tanpa Ekstensi .log

---

routes.php

Perubahan ini memperbaiki serangkaian masalah terkait halaman melihat log, termasuk error 404 dan permintaan untuk URL tanpa ekstensi .log.
- `routes.php`: Menyederhanakan definisi rute untuk melihat log, mengganti parameter opsional dengan dua rute eksplisit untuk menghindari ambiguitas pada router.
- `public/index.php`: Memperbaiki logika parsing URI untuk menangani `BASE_URL` dengan benar, memungkinkan aplikasi berfungsi di subdirektori.
- `src/Controllers/Admin/LogController.php`: Memperbarui controller untuk menangani nama file tanpa ekstensi dari URL dan memuat file yang benar.
- `src/Views/admin/logs/file_log.php`: Memperbarui semua tautan (sidebar, paginasi) untuk menggunakan struktur URL baru tanpa ekstensi `.log` dan `BASE_URL`.

Memperbaiki Routing dan URL untuk Halaman Log
