mieburungdara/tgbots

CHANGELOG.md, admin/webhook_manager.php, webhook.php
Commit ini mengimplementasikan kembali fitur manajemen webhook dengan perbaikan penting berdasarkan masukan Anda.
Perubahan utama:
- URL Webhook sekarang dibuat menggunakan ID Bot Telegram numerik yang diekstrak dari token (misalnya, `7715036030`), bukan ID database internal. Ini memastikan URL bersifat unik dan dapat diandalkan.
- Skrip `webhook.php` telah diperbarui untuk mencari bot di database dengan mencocokkan ID Bot Telegram ini di awal string token.
Fitur lainnya tetap sama:
- Tombol "Edit" pada daftar bot.
- Halaman manajemen bot baru (`admin/edit_bot.php`) dengan tombol untuk Set, Check, dan Delete webhook.
- Penggunaan AJAX dan modal untuk pengalaman pengguna yang lancar.
- Metode baru di kelas `TelegramAPI`.
- `CHANGELOG.md` diperbarui.
=> feat: Tambahkan manajemen webhook dari panel admin (Perbaikan)

CHANGELOG.md, admin/bots.php, admin/index.php, admin/logs.php, admin/settings.php, core/TelegramAPI.php, core/database.php, core/helpers.php, webhook.php
This commit introduces a centralized logging system and a user interface in the admin panel to view and manage logs.
Key changes:
- A new centralized logging function `app_log` has been added to `core/helpers.php`. It supports different log levels which are written to separate files in the new `logs/` directory.
- All previous `error_log` calls throughout the application have been refactored to use the new `app_log` function.
- A new log viewer page has been created at `admin/logs.php`. This page allows administrators to select a log file, view the last 20 entries, and clear the log file.
- The admin panel navigation has been updated across all pages to include a link to the new log viewer.
- The `CHANGELOG.md` has been updated to reflect these new features.
=> feat: Add centralized logging and admin log viewer

CHANGELOG.md, member/index.php
This commit adds specific logging for the member login functionality to improve monitoring and debugging capabilities.
Key changes:
- The `process_login_token` function in `member/index.php` now logs successful and failed login attempts.
- A new log file, `logs/member.log`, is created to store these specific logs, separating them from other application logs.
- The `CHANGELOG.md` has been updated to reflect this enhancement.
=> feat: Add logging to member login process

CHANGELOG.md, webhook.php
This commit adds more detailed logging to the `/login` command handler in `webhook.php`.
Key changes:
- The token creation process is now wrapped in a try-catch block to handle and log potential database errors.
- Logs are now created for the initiation of a token request, successful creation, and any failures.
- The `CHANGELOG.md` has been updated.
=> feat: Add logging to token creation process

CHANGELOG.md, admin/bots.php, admin/chat.php, admin/index.php, admin/logs.php, admin/settings.php, admin/users.php, migrations/003_add_bot_id_to_messages.sql, setup.sql, webhook.php
Menambahkan halaman `admin/users.php` baru yang memungkinkan admin untuk melihat, mencari, dan mengelola pengguna.
Fitur Utama:
- Menampilkan daftar pengguna yang dapat diurutkan dan dicari.
- Menampilkan bot yang terhubung dengan setiap pengguna, dengan tautan ke riwayat obrolan.
- Menambahkan tombol untuk memblokir/membuka blokir pengguna dari bot secara individual.
Sebagai bagian dari pekerjaan ini, beberapa halaman inti (`index.php`, `chat.php`) di-refactor agar kompatibel dengan skema database many-to-many yang baru. Skema `messages` juga diperbaiki dengan menambahkan `bot_id` untuk integritas data.
Menu navigasi di semua halaman admin telah diperbarui untuk menyertakan tautan ke halaman Pengguna yang baru.
=> feat: Buat halaman manajemen pengguna dengan fungsionalitas penuh

member/dashboard.php, member/index.php
Merefaktor file di direktori `/member` untuk memperbaiki alur login yang rusak setelah perubahan skema database.
Perubahan ini mencakup:
- Memperbarui `member/index.php` untuk menggunakan `user_id` dan mengatur `$_SESSION['member_user_id']` dengan benar.
- Memperbarui `member/dashboard.php` untuk memeriksa session `member_user_id` dan mengambil data dari tabel `users` (bukan `chats`).
=> fix: Perbaiki alur login member agar sesuai skema DB baru

admin/chat.php
Memperbarui halaman `admin/chat.php` untuk meningkatkan pengalaman pengguna saat melihat pesan media.
- Query utama sekarang melakukan `LEFT JOIN` ke `media_files` untuk mengambil detail media.
- Pesan media kini ditampilkan dengan ikon jenis media (foto, video, dll.) dan nama file.
- Menambahkan tombol 'Teruskan' di sebelah setiap pesan media yang masuk, yang memungkinkan admin untuk meneruskan media tersebut ke semua admin lain menggunakan fungsionalitas yang sudah ada.
=> feat: Tampilkan ikon media dan tombol teruskan di chat

HOWTO.md
This commit adds a HOWTO.md file that explains the user flows for the new media marketplace feature. It details the steps and commands for sellers, buyers, and admins.
=> docs: Add HOWTO.md for marketplace feature

webhook.php
This commit fixes a bug in the seller's media submission flow.
Previously, I would become unresponsive after the first media file was sent, failing to acknowledge subsequent files or the `/done` command.
The root cause was improper transaction management and state handling within the `webhook.php` script. The script was exiting prematurely after handling a media file, preventing the full state from being committed and blocking subsequent interactions.
The fix includes:
- Refactoring the main logic block to use a single transaction commit at the end.
- Removing premature `exit` calls within the `try...catch` block.
- Correcting the state-handling logic to ensure I provide a confirmation for every media file received.
=> fix: Correct seller media submission flow

webhook.php
This commit fixes a persistent bug where the `/done` command was not correctly terminating the `awaiting_media` state.
The root cause was that the `/done` command logic was located in the general command handler, which was not the most logical place for a state-specific command.
The fix refactors the state-handling logic:
- The `/done` command is now handled within the state machine, specifically in the `case 'awaiting_media'`, ensuring it's processed with the correct priority and context.
- Command checks for `/done`, `/cancel`, etc., were made more robust to prevent issues with extra characters.
- This new structure correctly transitions you to the `awaiting_description` state.
=> fix: Refactor state handling for seller flow

CHANGELOG.md, webhook.php
Per your request, this commit updates the generic `/start` command response.
The new welcome message is more informative and user-friendly. It now lists the main commands available to you (`/sell`, `/balance`, `/konten`, `/login`), provides brief instructions for each, and includes emojis to be more engaging.
=> feat(start): Update welcome message to be more informative

webhook.php
This commit refactors the main `webhook.php` controller to ensure correct variable scope and a clean, logical flow of execution.
Previously, due to incorrect merging of refactored code, the `$user_repo` variable was not being instantiated in the global scope of the script, leading to a fatal error when state-based conversation logic tried to access it.
This commit corrects the structure by:
1.  Ensuring all Repositories (BotRepository, UserRepository) are instantiated early in the script.
2.  Establishing a clear, linear flow:
- Validate input
- Initialize dependencies (DB, Repositories)
- Get or create user
- Delegate to the appropriate handler (State, Media, Callback, Message)
3.  This resolves the 500 Internal Server Error caused by the undefined variable.
=> Fix: Correct logic flow and variable scope in webhook.php

CHANGELOG.md, admin/bots.php, admin/channels.php, admin/database.php, admin/index.php, admin/logs.php, admin/media_logs.php, admin/roles.php, admin/users.php
- Memindahkan fitur migrasi database dari halaman Pengaturan ke halaman `database.php` yang baru.
- Mengganti nama `settings.php` menjadi `channels.php` agar fokus pada manajemen channel.
- Memperbarui semua tautan navigasi di panel admin untuk mencerminkan struktur menu yang baru.
=> Merapikan panel admin dengan memisahkan fungsionalitas.

CHANGELOG.md, admin/bot_manager.php, admin/bots.php, admin/edit_bot.php, core/TelegramAPI.php, migrations/015_update_bots_table.sql
- Menghapus input nama manual saat menambahkan bot baru.
- Mengimplementasikan panggilan ke metode API `getMe` untuk secara otomatis mengambil `first_name` dan `username` bot saat token ditambahkan.
- Menambahkan tombol "Get Me & Update" di halaman edit bot untuk memungkinkan admin menyinkronkan informasi bot kapan saja.
- Memperbarui skema tabel `bots` (mengganti nama `name` menjadi `first_name` dan menambahkan `username`) untuk menyelaraskan dengan data dari API Telegram.
=> Menyederhanakan proses penambahan dan pembaruan bot di panel admin.

CHANGELOG.md, admin/packages.php, core/database/PackageRepository.php, core/database/UserRepository.php, core/handlers/CallbackQueryHandler.php, core/handlers/MessageHandler.php, core/helpers.php, member/purchased.php, member/sold.php, migrations/018_add_public_ids.sql, migrations/populate_public_ids.php, webhook.php
- Menambahkan alur registrasi untuk penjual baru saat pertama kali menggunakan `/sell`.
- Menambahkan ID publik unik (4 huruf acak) untuk setiap penjual, disimpan di tabel `users`.
- Menambahkan nomor urut per penjual untuk setiap paket konten, disimpan di tabel `users`.
- Membuat ID publik untuk setiap paket dengan format `[ID_PENJUAL]_[NOMOR_URUT]`.
- Memperbarui semua antarmuka (bot, panel member, panel admin) untuk menggunakan ID publik yang baru.
- Menyediakan skrip back-fill untuk menghasilkan ID publik bagi data yang sudah ada.
=> Mengubah format ID konten menjadi `XXXX_YYYY` (ID Penjual + Nomor Urut).

CHANGELOG.md, core/handlers/MessageHandler.php
Commit ini mencakup beberapa pembaruan besar: satu fitur baru, tiga peningkatan, dan satu perbaikan bug kritis.
- **Handler Pesan yang Diedit**: Bot sekarang dapat mendeteksi saat Anda mengedit caption media dan menyinkronkannya ke database.
- **Refactoring Alur `/sell`**: Alur kerja perintah `/sell` dirombak total. Pembuatan paket dan ID sekarang ditunda sampai harga dikonfirmasi, membuat pembatalan lebih bersih dan efisien.
- **Prompt /sell Lebih Informatif**: Pesan permintaan harga sekarang menampilkan pratinjau deskripsi, rincian media per jenis dengan emoji, dan instruksi untuk `/cancel`.
- **Deteksi Caption Media Group**: Perintah `/sell` sekarang lebih pintar dalam mendeteksi caption dari album/media group.
- **Bug Transaksi Bersarang**: Memperbaiki error kritis "There is already …
=> Fitur & Perbaikan: Alur /sell, Handler Edit, & Prompt Informatif

CHANGELOG.md, admin/index.php
Commit ini mencakup perombakan besar pada fungsionalitas penjualan dan beberapa perbaikan penting.
- **Perintah `/addmedia`**: Penjual sekarang dapat menambahkan media ke paket yang sedang dibuat, atau ke paket yang sudah ada menggunakan `/addmedia <ID>`.
- **Handler Pesan yang Diedit**: Bot sekarang dapat mendeteksi dan menyinkronkan caption yang diedit.
- **Refactoring Alur `/sell`**: Alur kerja penjualan dirombak total untuk membuat proses pembatalan lebih bersih dan efisien.
- **Optimisasi Penyalinan Album**: Proses penyalinan album sekarang lebih cepat menggunakan `copyMessages`.
- **Optimisasi Skema DB**: Kolom `file_id` yang tidak lagi diperlukan telah dihapus dari tabel `media_files`.
- **Prompt /sell Lebih Informatif**: Pesan permintaan harga sekarang menampilkan rincian lengkap …
=> Fitur & Perbaikan: Alur /sell, Edit Paket, & Fix Panel Admin

CHANGELOG.md, admin/bots.php, admin/channels.php, admin/database.php, admin/index.php, admin/logs.php, admin/media_logs.php, admin/packages.php, admin/roles.php, admin/telegram_logs.php, admin/users.php, core/TelegramAPI.php, core/database/TelegramErrorLogRepository.php, core/database/UserRepository.php, migrations/020_create_telegram_error_logs_table.sql, migrations/021_add_status_to_users_table.sql, webhook.php
Merombak total sistem penanganan kesalahan untuk semua interaksi dengan API Telegram, menambahkan logging ke database, dan menyediakan antarmuka admin untuk pemantauan.
Fitur Utama:
- Menambahkan tabel `telegram_error_logs` baru untuk mencatat semua kegagalan permintaan API secara persisten.
- Menambahkan tabel `users` dengan kolom `status` untuk melacak pengguna yang aktif atau diblokir.
- Membuat halaman baru di panel admin (`admin/telegram_logs.php`) untuk menampilkan log kesalahan dengan paginasi.
- Merombak `TelegramAPI.php` untuk menggunakan blok `try-catch`, menangani kesalahan koneksi cURL dan respons error dari API Telegram secara tangguh.
- Menambahkan logika spesifik untuk menangani kode error 400, 403, dan 429.
- Saat bot diblokir oleh pengguna (error 403), status pengguna di …
=> Implementasi Penanganan Error Lanjutan untuk API Telegram

admin/partials/header.php
This commit includes a fix for the admin page header layout and consolidates several critical bug fixes for the API testing tools.
- **Header Layout:** Adds a title to the admin header, allowing the flexbox container to render correctly and create a balanced layout.
- **Argument Handling:** Resolves a critical bug in the API handler that caused incorrect parameter ordering when optional parameters were skipped.
- **UI Bugs:** Fixes a JavaScript bug in the API tester that displayed 'undefined' for nested parameter labels and input placeholders.
- **Type Safety:** Adds server-side type-casting for `message_thread_id` to ensure it is an integer.
- **Error Reporting:** Improves API error handling to return detailed error objects instead of a generic `false`.
- **Defaults:** Sets the default …
=> Fix: Improve admin header layout and resolve various API bugs

core/handlers/MessageHandler.php
Menambahkan logging rinci ke `MessageHandler` untuk melacak alur deteksi dan penanganan pesan yang di-forward secara otomatis dari channel.
Ini bertujuan untuk men-debug masalah di mana pesan tidak terdeteksi seperti yang dilaporkan.
- Menambahkan log di `handle()` untuk verifikasi deteksi `is_automatic_forward`.
- Menambahkan log di `handleAutomaticForward()` untuk melacak setiap langkah: pembacaan `forward_origin`, query database, dan pengiriman balasan.
=> Debug: Tambahkan logging untuk alur balasan otomatis

admin/channel_chat.php, migrations/029_add_types_to_messages.sql, webhook.php
- Menambahkan migrasi DB untuk membuat kolom `chat_type` dan `update_type` di tabel `messages`.
- Memperbarui `webhook.php` untuk mengisi kolom-kolom baru ini saat menyimpan pesan.
- Menampilkan `chat_type` dan `update_type` di halaman admin `channel_chat.php`.
=> Fitur: Tambahkan `chat_type` dan `update_type` ke pesan

core/handlers/MessageHandler.php
- Mengubah `handleStartCommand` untuk memeriksa apakah pengguna sudah membeli item.
- Jika sudah, tampilkan pesan 'Anda sudah memiliki item' dengan tombol 'Lihat Konten'.
- Jika belum, lanjutkan ke alur pembelian.
- Ini mencegah error 'item tidak tersedia' saat mengakses kembali item yang sudah dibeli.
=> Fix: Tangani kasus pembelian ulang item via deep link

core/handlers/MessageHandler.php
Merombak `handleStartCommand` untuk menangani deep link dengan benar.
- Memeriksa apakah pengguna adalah pemilik atau sudah membeli item.
- Menampilkan tombol yang sesuai untuk setiap kasus (lihat konten, post ke channel, beli).
- Mencegah pesan error 'item tidak tersedia' yang keliru untuk pemilik dan pembeli.
=> Fix: Alur /start untuk pemilik konten & pembeli

admin/logs.php
This commit improves the user interface and experience of the database logs viewer at `admin/logs.php`.
The following enhancements have been implemented:
1.  **Row-Level Color Coding**: Each log row now has a colored left border corresponding to its log level (e.g., red for 'error', blue for 'debug'). This allows for easier and faster visual scanning of important log entries.
2.  **Collapsible Context Data**: The JSON context data, which can be very long, is now hidden by default. A 'Show/Hide' button has been added to each row, allowing the user to toggle the visibility of the context details on demand. This makes the overall table view much cleaner and more readable.
=> feat(admin): Enhance UI for logs page

admin/debug_feed.php, core/database/RawUpdateRepository.php, partials/footer.php, partials/header.php
This commit completely revamps the admin debug feed page (`admin/debug_feed.php`) to be more usable, powerful, and visually appealing.
The following features have been implemented:
1.  **Pagination**: The page is no longer limited to the last 100 updates. A full pagination system has been added, allowing administrators to browse through the entire history of raw Telegram updates.
2.  **Collapsible Entries**: Each update is now presented as a collapsible card. The user can see a clean list of update IDs and timestamps and click to expand any entry to see the full JSON payload.
3.  **JSON Syntax Highlighting**: The JSON payloads are no longer plain text. The Prism.js library has been integrated to provide full color syntax highlighting, making the data significantly easier to read and parse …
=> feat(admin): Overhaul UI for debug feed page

core/database/AnalyticsRepository.php, member/dashboard.php, partials/header.php
This commit completely revamps the member dashboard to be more informative and engaging.
Key changes:
- Adds a 30-day sales trend chart using Chart.js.
- Displays top-selling items for the user.
- Includes a summary of user's purchase statistics.
- Redesigns the layout using a modern grid system and cards for better readability.
- Adds a new method to AnalyticsRepository to fetch top-selling items for a specific seller.
=> feat: Make member dashboard more informative and visually appealing

migrations/035_switch_to_telegram_ids.php
- Memodifikasi `migrations/035_switch_to_telegram_ids.php` untuk memeriksa `$pdo->inTransaction()` sebelum memulai transaksi baru.
- Skrip sekarang hanya akan mengelola transaksinya sendiri jika tidak dijalankan oleh skrip runner lain.
- Memastikan error dilemparkan kembali (throw) agar dapat ditangani oleh `catch` block di skrip pemanggil.
- Ini memperbaiki error `There is no active transaction` dan memungkinkan runner migrasi CLI untuk menyelesaikan semua migrasi dengan aman.
=> Perbaikan: Cegah nested transaction di skrip migrasi 035

xoradmin.php
This commit refactors `xoradmin.php` to fix a bug where AJAX requests would fail with a JSON parsing error if the user's session had expired.
The script is restructured to handle all AJAX requests at the top, before any HTML is rendered. This new handler block now checks for authentication and returns a proper JSON error if the session is invalid, instead of letting the script render the full HTML login page. This ensures the JavaScript client always receives a valid JSON response.
=> fix: Correctly handle AJAX auth in xoradmin

xoradmin.php, xoradminapi.php
This commit refactors the `xoradmin.php` tool by separating the backend AJAX handling logic into a new, dedicated `xoradminapi.php` file.
- Created `xoradminapi.php` to handle all AJAX actions (get_me, set/check/delete webhook).
- Moved the relevant PHP logic from `xoradmin.php` to the new API file.
- Updated the JavaScript `fetch` call in `xoradmin.php` to point to the new `xoradminapi.php` endpoint.
This change improves code organization and follows the principle of Separation of Concerns, making the tool cleaner and more maintainable.
=> refactor: Separate xoradmin API logic into its own file

README.md
This commit adds a new, detailed README.md file to the project. The file includes:
- A project description
- A list of key features
- Step-by-step installation instructions
- A guide on how to use the bot for both sellers and buyers
- Information about the admin panel and commands
The README is written in Indonesian, as requested by the project guidelines.
=> feat: Add comprehensive README.md file

CHANGELOG.md, admin/api/get_sales_log.php, admin/auth.php, admin/balance.php, admin/channel_chat.php, admin/chat.php, core/handlers/CallbackQueryHandler.php, core/handlers/MediaHandler.php, core/handlers/MessageHandler.php, member/dashboard.php
Melakukan audit dan perbaikan massal untuk menyelesaikan serangkaian error fatal (`500 Internal Server Error`, `Column not found`, `Invalid Token`) yang disebabkan oleh penggunaan nama kolom yang tidak konsisten untuk ID pengguna (`id` vs. `telegram_id`) di seluruh basis kode.
Masalah ini berasal dari migrasi skema database yang tampaknya telah dimulai tetapi tidak pernah diterapkan pada lingkungan produksi, meninggalkan kode dalam keadaan setengah-migrasi yang tidak stabil.
Perbaikan ini menyelaraskan seluruh basis kode aplikasi untuk secara konsisten menggunakan `id` sebagai primary key pengguna, sesuai dengan skema database yang aktif. Perubahan dilakukan di berbagai file, termasuk:
- Handler inti (`UpdateDispatcher`, `MessageHandler`, `CallbackQueryHandler`, `MediaHandler`)
- …
=> Perbaiki: Inkonsistensi ID Pengguna di Seluruh Kode

CHANGELOG.md, xoradmin.php, xoradminapi.php
Menambahkan fitur sederhana untuk memberikan peran 'Admin' kepada pengguna langsung dari panel `xoradmin.php`, sesuai permintaan pengguna untuk menyederhanakan manajemen peran.
- Menambahkan tab "Manajemen Peran" baru di `xoradmin.php`.
- Menampilkan daftar pengguna beserta perannya saat ini.
- Menyediakan tombol "Jadikan Admin" untuk pengguna yang belum memiliki peran tersebut.
- Mengimplementasikan endpoint API `make_admin` di `xoradminapi.php` untuk menangani logika pemberian peran.
- Memperbarui `CHANGELOG.md` untuk mencatat fitur baru ini.
=> Fitur: Tambah fungsionalitas 'Jadikan Admin' di XOR Admin Panel.

admin/chat.php
Memperbaiki bug kritis di `admin/chat.php` di mana riwayat pesan tidak muncul meskipun `COUNT(*)` menunjukkan ada pesan.
- **Penyebab**: Ditemukan bahwa mengurutkan (`ORDER BY`) berdasarkan kolom `created_at` menyebabkan query `SELECT` gagal tanpa error. Ini kemungkinan besar karena ada data yang rusak atau tidak valid (misalnya, '0000-00-00 ...') di kolom `created_at` untuk beberapa baris. Query yang mengurutkan berdasarkan `id` berhasil.
- **Solusi**: Mengubah klausa `ORDER BY` di `admin/chat.php` dari `created_at DESC` menjadi `id DESC` agar konsisten dengan query lain yang berfungsi di aplikasi dan untuk menghindari penggunaan kolom yang berpotensi rusak untuk pengurutan.
feat: Menambahkan fitur debug query di halaman chat
- Menambahkan bagian 'Info Debug Kueri' yang dapat diciutkan …
=> fix: Riwayat chat tidak muncul karena ORDER BY pada kolom corrupt

admin/index.php
Menambahkan bagian 'Info Debug Kueri' yang dapat diciutkan di `admin/index.php`. Fitur ini menampilkan kueri SQL mentah dan parameter yang digunakan untuk mengambil daftar percakapan.
Ini diimplementasikan sesuai permintaan pengguna untuk membantu men-debug masalah di mana `admin/chat.php` gagal mengambil data sementara `admin/index.php` berhasil.
=> feat: Menambahkan fitur debug kueri di halaman utama admin

admin/api/verify_channel_bot.php, core/database/BotRepository.php
Memperbaiki error fatal `Call to undefined method BotRepository::getAllBots()` yang terjadi di halaman `admin/channels.php`.
Perubahan:
- Menambahkan metode `getAllBots()` yang hilang ke `core/database/BotRepository.php` untuk mengambil semua data bot.
- Memperbaiki pemanggilan metode yang salah di `admin/api/verify_channel_bot.php`, mengubah `findById` menjadi `findBotByTelegramId` agar sesuai dengan metode yang ada di `BotRepository`.
=> Perbaikan: Atasi Error Fatal 'Undefined Method'

admin/api/update_channel_info.php, admin/channels.php, core/database/PrivateChannelRepository.php
Menambahkan fungsionalitas untuk menyinkronkan informasi channel dari Telegram.
Perubahan:
- Menambahkan tombol "Refresh" pada setiap baris di tabel `admin/channels.php`.
- Membuat endpoint API baru `admin/api/update_channel_info.php` yang memanggil metode `getChat` dari API Telegram untuk mendapatkan data channel terbaru.
- Nama channel di database akan diperbarui sesuai dengan respons dari API.
- Tampilan nama channel di tabel akan diperbarui secara dinamis setelah sinkronisasi berhasil.
- Menambahkan metode `updateNameByTelegramId` ke `PrivateChannelRepository`.
=> Fitur: Tombol Refresh Info Channel

CHANGELOG.md, src/Controllers/Admin/XorAdminController.php
Menerapkan dua peningkatan utama:
1. Halaman "Akses Ditolak" yang lebih baik: Mengganti pesan teks biasa dengan halaman HTML yang ramah pengguna, lengkap dengan instruksi login dan tautan dinamis ke bot.
2. Perbaikan Keamanan: Mengganti perbandingan password yang rentan (`===`) dengan fungsi `hash_equals()` di XorAdminController untuk mencegah serangan waktu (timing attacks).
Perubahan ini meningkatkan pengalaman pengguna dan keamanan aplikasi.
=> Fitur: Halaman Akses Ditolak & Perbaikan Keamanan

CHANGELOG.md, src/Controllers/Admin/RoleController.php
Menerapkan serangkaian perbaikan dan fitur utama berdasarkan beberapa isu yang ada:
1.  **Fitur Halaman Akses Ditolak**: Mengganti pesan `die()` dengan halaman HTML yang ramah pengguna saat akses ditolak, memberikan instruksi login yang jelas dan tautan dinamis ke bot.
2.  **Perbaikan Keamanan**:
- Mengganti perbandingan password `===` yang rentan terhadap serangan waktu (timing attack) dengan fungsi `hash_equals()` di `XorAdminController`.
- Menambahkan sanitasi input `htmlspecialchars` untuk `role_name` di `RoleController` untuk mencegah XSS.
- Menambahkan validasi integer yang ketat untuk `role_id` di `RoleController` menggunakan `filter_input`.
3.  **Refactoring & Pembersihan Kode**:
- Menghapus kode `if ($result === false)` yang redundan dari `XorAdminController`.
- Memusatkan logika …
=> Fitur & Perbaikan: Peningkatan UI, Keamanan, dan Kode

CHANGELOG.md, src/Views/admin/debug_feed/index.php
Melakukan refactoring pada view `debug_feed/index.php` untuk menyelaraskan dengan praktik di seluruh aplikasi.
Menghapus definisi variabel lokal `$current_page` dan `$total_pages`. Logika paginasi sekarang secara langsung menggunakan nilai dari array `$data['pagination']`, yaitu `$data['pagination']['current_page']` dan `$data['pagination']['total_pages']`.
Perubahan ini memastikan bahwa semua view yang menggunakan paginasi mengikuti pola yang konsisten, meningkatkan keterbacaan dan pemeliharaan kode.
=> Peningkatan: Konsistensi variabel paginasi di Debug Feed

CHANGELOG.md, src/Views/admin/storage_channels/index.php, src/Views/admin/xoradmin/login.php, src/Views/auth/access_denied.php, src/Views/member/login/index.php
Melakukan refactoring pada beberapa file view untuk mengganti tag echo panjang `<?php echo` dengan tag echo pendek `<?=`.
Perubahan ini dilakukan untuk menyelaraskan kode dengan standar PSR-12 dan praktik yang sudah ada di seluruh proyek, yang bertujuan untuk meningkatkan keterbacaan dan konsistensi kode.
=> Peningkatan: Gunakan tag echo pendek (<?=) untuk konsistensi

CHANGELOG.md, src/Views/admin/balance/index.php, src/Views/admin/chat/channel.php, src/Views/admin/chat/index.php, src/Views/admin/debug_feed/index.php, src/Views/admin/logs/app.php, src/Views/admin/logs/telegram.php, src/Views/admin/users/index.php
Melakukan refactoring pada logika paginasi di beberapa file view untuk meningkatkan keterbacaan dan konsistensi.
Memperkenalkan variabel lokal `$currentPage` dan `$totalPages` di dalam blok paginasi untuk menghindari pengulangan pemanggilan array dan membuat kode lebih bersih, sejalan dengan prinsip DRY.
=> Peningkatan: Keterbacaan kode paginasi di view

CHANGELOG.md, INSTALL.md
Menambahkan file `INSTALL.md` baru yang berisi panduan instalasi yang lengkap dan terperinci untuk pengguna baru.
Panduan ini mencakup:
- Persyaratan server
- Konfigurasi aplikasi (`config.php`)
- Pengaturan database (`setup.sql`)
- Menjalankan migrasi database
- Konfigurasi web server untuk Apache dan Nginx
- Prosedur untuk menyiapkan bot Telegram dan mengatur webhook melalui panel admin.
Selain itu, `CHANGELOG.md` telah diperbarui untuk mencatat penambahan dokumentasi baru ini.
=> Fitur: Tambah panduan instalasi (INSTALL.md)

routes.php, src/Controllers/HomeController.php, src/Views/maintenance.php
Menambahkan halaman "sedang dalam perbaikan" yang akan ditampilkan saat pengguna mengakses URL root situs.
- Membuat `HomeController.php` baru untuk menangani logika halaman utama.
- Membuat view `maintenance.php` dengan pesan dan styling sederhana.
- Menambahkan route baru di `routes.php` untuk URL root (`''`) yang mengarah ke controller baru.
- Mengatur response code ke 503 (Service Unavailable) yang sesuai untuk halaman perbaikan.
=> Fitur: Tambah halaman "sedang dalam perbaikan"

core/Router.php
Merombak total `core/Router.php` untuk menambahkan dukungan terhadap rute dinamis dengan parameter (misalnya, `/webhook/{id}`).
Perubahan meliputi:
- Mengganti logika pencocokan URI dari `array_key_exists` yang kaku menjadi perulangan dengan `preg_match` berbasis regular expression.
- Rute dengan placeholder seperti `{id}` sekarang secara otomatis diubah menjadi pola regex.
- Nilai dari placeholder diekstrak menggunakan "named capture groups" dan diteruskan sebagai array asosiatif ke metode controller yang sesuai.
- Metode `callAction` diperbarui untuk menerima dan meneruskan array parameter ini.
Perbaikan ini mengatasi kelemahan fundamental dalam sistem routing dan memungkinkan fungsionalitas seperti webhook untuk bekerja sebagaimana mestinya.
=> Fitur: Refactor Router untuk mendukung rute dinamis

core/Router.php
Menambahkan validasi di dalam metode `direct()` untuk memastikan string controller rute mengandung karakter '@'.
Jika formatnya salah (misalnya, 'MyController' bukan 'MyController@action'), sebuah Exception yang jelas akan dilempar. Ini mencegah error "Undefined offset" dan membuat router lebih tangguh terhadap kesalahan konfigurasi rute.
Perbaikan ini berdasarkan masukan dari pengguna.
=> Perbaikan: Tambah validasi format controller di Router

public/index.php
Menambahkan mekanisme penanganan error yang komprehensif di `public/index.php` untuk membantu mendiagnosis error fatal yang sulit dilacak.
- Penggunaan `set_exception_handler` untuk menangkap semua uncaught exception.
- Penggunaan `set_error_handler` untuk mengubah semua error PHP menjadi log.
- Penggunaan `register_shutdown_function` untuk menangkap error fatal (E_ERROR).
Semua error yang tertangkap sekarang akan dicatat menggunakan fungsi `app_log()` yang sudah ada, sehingga dapat diperiksa melalui panel admin.
=> Fitur: Implementasi global error & exception handler

core/handlers/CallbackQueryHandler.php
This commit completes the feature set for the /rate and /tanya commands by adding the admin moderation workflow.
Key changes:
1.  **Admin Action Routing**:
*   The `handle` method in `CallbackQueryHandler.php` has been updated to recognize and route callbacks starting with `admin_reject_` and `admin_ban_`.
2.  **Rejection Logic**:
*   A new `handleAdminRejection` method was added to `CallbackQueryHandler.php`.
*   This method updates the post status to 'rejected', notifies the user with the reason for rejection, and updates the message in the admin channel to reflect the action.
3.  **Ban Logic**:
*   A new `handleAdminBan` method was added to `CallbackQueryHandler.php`.
*   This method updates the user's status to 'blocked' in the database, rejects any associated post, notifies the user …
=> feat: Implement admin moderation workflow

core/handlers/CallbackQueryHandler.php, src/Handlers/RateHandler.php, src/Handlers/TanyaHandler.php
This commit completes the feature set for the /rate and /tanya commands by enhancing the admin moderation workflow and adding manual approval capabilities.
Key changes:
1.  **Enhanced Moderation Message**:
*   The message sent to the admin moderation channel is no longer a simple forward. It is now a new message containing a detailed caption with post information (Public ID, User ID, etc.) and the original user-submitted content.
*   This new message includes an inline keyboard with buttons for `Approve`, `Reject` (with quick reasons), and `Ban User`.
2.  **Manual Approval Logic**:
*   A new `handleAdminApproval` method has been added to `CallbackQueryHandler.php` to handle the `Approve` button.
*   This method performs the same actions as the auto-approval cronjob: it updates the post …
=> feat: Enhance admin workflow and add manual approval

CHANGELOG.md, src/Controllers/Admin/DatabaseController.php, src/Views/admin/database/check.php
Menambahkan fitur canggih di panel admin (`Admin > Database > Periksa Skema`) untuk membandingkan skema database live dengan file `updated_schema.sql`.
Fitur ini mampu mendeteksi berbagai jenis perbedaan:
- Tabel yang hilang (di database live)
- Tabel tambahan (tidak ada di file skema)
- Kolom yang hilang di dalam tabel
- Kolom tambahan di dalam tabel
- Kolom yang definisinya (tipe data, nullability, default, dll.) tidak cocok
Untuk setiap perbedaan yang ditemukan, alat ini secara otomatis menghasilkan query SQL (`CREATE TABLE`, `DROP TABLE`, `ALTER TABLE`) yang dapat disalin oleh admin untuk menyinkronkan database secara manual.
Tampilan laporan juga telah didesain ulang untuk menyajikan semua perbedaan ini dalam format yang jelas dan terstruktur.
=> Fitur: Menambahkan pemeriksa skema database komprehensif.

CHANGELOG.md, core/database.php, core/database/AnalyticsRepository.php, core/database/ChannelPostPackageRepository.php, core/database/MediaPackageRepository.php, core/database/SaleRepository.php, core/handlers/CallbackQueryHandler.php, core/handlers/InlineQueryHandler.php, core/handlers/MessageHandler.php, cron/auto_approve.php, routes.php, src/Controllers/Admin/BalanceController.php, src/Controllers/Admin/MediaPackageController.php, src/Controllers/Member/ContentController.php, src/Controllers/Member/TransactionController.php, src/Handlers/RateHandler.php, src/Handlers/TanyaHandler.php, updated_schema.sql
Melakukan refactoring di seluruh basis kode untuk mengganti semua referensi ke tabel `post_packages` yang lama menjadi `media_packages` agar konsisten dengan skema database terbaru.
- Mengganti nama `PostPackageRepository` menjadi `MediaPackageRepository`.
- Memperbarui semua query SQL yang relevan.
- Menyesuaikan semua `use` statement dan instansiasi kelas di seluruh aplikasi.
Tindakan ini menghilangkan inkonsistensi antara kode dan skema, memperbaiki bug, dan meningkatkan keterbacaan serta pemeliharaan kode.
=> Refactor: Menyelaraskan penggunaan tabel `media_packages`.

CHANGELOG.md, src/Controllers/Admin/DatabaseController.php
Commit ini mencakup perbaikan definitif untuk semua masalah yang dilaporkan, menghasilkan fitur pemeriksa skema dan migrasi yang andal.
1.  **Perbaikan Runner Migrasi**: Menghapus logika transaksi (`beginTransaction`, `commit`, `rollBack`) dari `DatabaseController` untuk menyelesaikan error "There is no active transaction" yang disebabkan oleh implicit commit dari DDL.
2.  **Perbaikan Skrip Migrasi**: Memperbaiki syntax error pada skrip migrasi dengan mengganti logika pemeriksaan kolom yang tidak valid dengan metode `in_array()` yang aman.
3.  **Parser Skema yang Andal**: Menyertakan parser skema yang telah ditulis ulang sepenuhnya, yang sekarang menggunakan pendekatan baris-per-baris yang stabil.
4.  **Refactoring Kode**: Menyertakan semua refactoring `post_packages` -> …
=> Fix: Menyelesaikan perbaikan migrasi dan sinkronisasi skema akhir

CHANGELOG.md, src/Views/admin/bots/edit.php
Commit ini mencakup perbaikan definitif untuk semua masalah yang dilaporkan selama sesi, menghasilkan basis kode yang stabil dan sinkron.
1.  **Perbaikan PHP Warning**: Memperbaiki `Warning: Undefined array key` di `src/Views/admin/bots/edit.php` dengan menambahkan pemeriksaan `empty()` dan null coalescing.
2.  **Perbaikan Runner Migrasi**: Menghapus logika transaksi yang salah dari `DatabaseController` untuk menyelesaikan error "There is no active transaction".
3.  **Perbaikan Skrip Migrasi**: Memperbaiki syntax error pada skrip migrasi dengan menggunakan metode pemeriksaan kolom yang valid.
4.  **Parser Skema yang Andal**: Menyertakan parser skema yang telah ditulis ulang sepenuhnya menggunakan pendekatan baris-per-baris yang stabil.
5.  **Refactoring Kode**: …
=> Fix: Menyelesaikan perbaikan akhir dan refactoring

CHANGELOG.md, src/Controllers/Admin/DatabaseController.php
Commit ini mencakup perbaikan definitif untuk `Parse error` yang dilaporkan, dan menggabungkan semua fitur dan perbaikan yang telah dikerjakan.
- **Perbaikan Parse Error**: Memperbaiki kesalahan sintaks di `DatabaseController.php` dengan menggunakan interpolasi variabel yang lebih aman untuk mencegah error pada lingkungan PHP tertentu.
- **Fitur Manajemen Channel**: Menyertakan implementasi penuh dari sistem manajemen channel berbasis fitur, termasuk:
- Database migration untuk tabel `feature_channels`.
- Fungsionalitas CRUD penuh di panel admin.
- Perintah `/register_channel` yang diperbarui untuk member.
- Penghapusan sistem `seller_sales_channels` yang usang.
- **Peningkatan UX**: Menyertakan bantuan kontekstual untuk `/help` dan saran bot yang lebih cerdas.
- …
=> Fix: Mengatasi Parse Error dan Menyelesaikan Fitur Channel

src/Controllers/Admin/DatabaseController.php
1.  **Fix Member Token-Based Login:** The member login was failing due to an incorrect token validation check that was susceptible to timezone differences between the web server and database server. The logic in `Member/LoginController.php` has been replaced with a single, robust SQL query that validates the token, checks its 5-minute expiration, and ensures the user has the 'Member' role directly in the database.
2.  **Refactor Admin Panel to /xoradmin:** The entire admin panel has been consolidated and moved from `/admin` to `/xoradmin`.
- **Password Authentication:** The token-based login for admins has been replaced with a standard, static password-based login system. A new `Admin/LoginController.php` handles the login, and a `BaseController.php` protects all admin pages by checking …
=> This commit addresses two main issues:

CHANGELOG.md, routes.php, src/Controllers/Member/ContentController.php, src/Views/member/content/channels.php
Perubahan ini mencakup dua perbaikan utama berdasarkan permintaan pengguna:
1.  **Penyatuan Alur Login (Lanjutan):**
- Menghapus logika kondisional pada perintah `/login` di `MessageHandler.php`. Semua pengguna sekarang menerima pesan dan tautan login yang sama dan konsisten.
- Ini melengkapi perbaikan sebelumnya pada `LoginController` untuk menciptakan alur login yang sepenuhnya terpadu tanpa batasan waktu atau peran.
2.  **Penambahan Halaman Member Channels:**
- Memperbaiki error 404 pada rute `/member/channels`.
- Menambahkan metode `channels()` baru ke `ContentController.php` untuk mengambil data channel jualan milik pengguna.
- Membuat view baru di `src/Views/member/content/channels.php` untuk menampilkan informasi channel.
- Mendaftarkan rute baru di `routes.php`.
=> Perbaiki: Perbaiki Alur Login & Tambah Halaman Member Channels

CHANGELOG.md, core/database/BotRepository.php, src/Controllers/Member/ContentController.php, src/Views/member/content/channels.php
Selesaikan serangkaian permintaan untuk meningkatkan panel member dan memperbaiki alur login.
1.  **Fitur Manajemen Channel Member (`/member/channels`):**
-   Memperbaiki error 404 dengan menambahkan rute, metode controller, dan view baru untuk halaman `/member/channels`.
-   Member sekarang dapat mendaftarkan atau memperbarui channel jualan mereka langsung dari antarmuka web.
-   Menambahkan formulir yang memungkinkan member memasukkan ID channel & grup, dan memilih bot pengelola dari daftar bot 'sell' yang tersedia.
-   Logika backend di `ContentController@registerChannel` memvalidasi input dan memverifikasi melalui API Telegram bahwa bot yang dipilih adalah admin di channel dan grup sebelum menyimpan.
2.  **Perbaikan Alur Login:**
-   Menghapus validasi masa berlaku …
=> Fitur: Manajemen Channel Member & Perbaikan Alur Login

core/helpers.php
- Fixes an issue where members could not log in with a token from the Telegram bot by removing time and role-based validation.
- Unifies the /login command response in the bot for all user roles.
- Adds a new page for members to view their registered channels.
- Implements a form for members to register new channels via the web interface.
- Allows members to select which bot manages their channel from a list of available bots.
- Adds a missing global `redirect()` helper function to prevent fatal errors.
=> feat: Implement member channel management and fix login issues

src/Views/layouts/member_layout.php
This commit bundles a large series of features and bug fixes to enhance the member experience and application stability.
Key Features & Enhancements:
- New member-facing page to register and manage sales channels.
- Automatic on-the-fly registration for members as sellers.
- Verification of channel ownership by checking member's admin status.
- Increased seller ID length to 5 characters with guaranteed uniqueness.
- Rate-limiting on the channel registration form to prevent API spam.
- UI improvements with a collapsible edit form.
Bug Fixes:
- Resolved member login issues by removing token expiration/role checks.
- Fixed multiple fatal errors related to missing helper functions, incorrect class instantiation, and uninitialized properties.
- Fixed a non-functional 'Edit' button by adding …
=> feat: Implement comprehensive member features and fixes

CHANGELOG.md, core/handlers/MessageHandler.php
This commit introduces a major overhaul of the sales channel functionality, including multi-channel support, moderation fixes, and an improved user interface.
Key changes:
1.  **Multi-Channel Support**:
-   Sellers can now register, manage, and delete multiple sales channels via the member panel.
-   The backend logic (Repository, Controllers, Handlers) has been updated to support multiple channels per user.
-   When posting content, sellers with multiple channels are now prompted to select a destination channel.
2.  **Sell Feature Moderation Fix**:
-   The `/sell` command now bypasses manual moderation entirely. New packages are created with an `available` status by default.
-   The channel registration logic now correctly sets `moderation_channel_id` to `NULL` for `sell` feature …
=> Feat: Overhaul sales channel management and moderation

core/handlers/StateHandler.php, core/handlers/StateRouter.php, core/handlers/States/AwaitingPriceState.php, core/handlers/States/StateInterface.php
The StateHandler class has been refactored to use the State design pattern. This improves modularity and makes it easier to add and manage new user states in the future.
The key changes include:
- Introduced a StateInterface and a StateRouter.
- Each user state's logic is now encapsulated in its own dedicated class within the 'core/handlers/States' directory (e.g., AwaitingPriceState).
- The main StateHandler now uses the StateRouter to delegate all state-specific logic.
=> refactor: Decompose StateHandler using State Pattern

core/handlers/States/AwaitingPriceState.php
Resolves a `MESSAGE_ID_INVALID` error by correcting the source of the copy operation in the `backupMedia` function.
Based on user feedback, the previous logic was flawed. It attempted to copy media from an intermediate storage channel, which was incorrect. The intended workflow is to copy the media directly from the user's private chat after a price has been set.
This commit refactors the `backupMedia` function in `AwaitingPriceState.php` to:
1. Group media files by their original `chat_id` (the user's chat).
2. Use the original `message_id`s as the source for the copy.
3. Copy the media to the designated backup channel.
4. Update the `storage_channel_id` and `storage_message_id` fields in the database with the location of the new copy.
This aligns the bot's behavior with the user's …
=> Fix: Use original user chat as source for media backup

core/handlers/Commands/KontenCommand.php
This commit reverts a previous change that removed the inline keyboard buttons for sellers when using the /konten command.
Based on direct user feedback, the desired behavior is for the bot to send the detailed content report AND the content preview with the 'Lihat Selengkapnya' and 'Post ke Channel' buttons.
This change removes the 'return' statement that was causing the premature exit and restores the logic for the seller-specific buttons, while retaining the try-catch block for error handling.
=> fix: Restore seller buttons in KontenCommand

public/index.php, src/Views/admin/logs/file_log.php
Perubahan ini memperbaiki bug 404 yang terjadi saat mengakses file log di lingkungan subdirektori.
- Memperbarui `public/index.php` untuk memproses URI permintaan dengan benar dengan menghapus `BASE_URL` sebelum meneruskannya ke router.
- Memperbarui `src/Views/admin/logs/file_log.php` untuk menambahkan `BASE_URL` pada semua tautan yang dibuat (lihat log, hapus log, dan paginasi), memastikan URL yang benar dibuat.
=> Memperbaiki Penanganan BASE_URL untuk Routing dan Tautan

src/Controllers/Admin/LogController.php, src/Views/layouts/admin_layout.php
Mengimplementasikan permintaan pengguna agar konten log dimuat di sisi kanan halaman tanpa perlu memuat ulang seluruh halaman.
- `src/Controllers/Admin/LogController.php`: Diperbarui untuk mendeteksi permintaan AJAX dan hanya mengirimkan konten parsial (tanpa layout) jika diminta.
- `src/Views/layouts/admin_layout.php`: Menambahkan JavaScript untuk mencegat klik pada tautan log, mengambil konten secara asinkron menggunakan Fetch API, dan menyuntikkannya ke area konten utama. Juga menggunakan History API untuk memperbarui URL.
=> Menambahkan Pemuatan Dinamis (AJAX) untuk Penampil Log
